package com.hamstrack.common.security;

import com.hamstrack.common.config.AppProperties;
import com.hamstrack.common.config.CspProperties;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * <strong>{@code CSP_POLICY} may not name a report path this instance does not serve</strong>
 * (HD-264).
 *
 * <p>"A {@code report-uri} that 404s is impossible by construction" is claimed in five places, and
 * the construction behind it — one property deciding both the clause and the endpoint — only ever
 * covered the <em>built-in</em> policy. An override replaces the directive string wholesale without
 * consulting the sink, and the likeliest reason anybody sets one is copying an observed Cloud header
 * onto a DC box: that header names this path, DC ships the sink off, and every violation the browser
 * saw would then POST to a path that answers {@code 405}. The claim is worth more than the override,
 * so the override loses — at startup, where an operator is still reading output.
 *
 * <p>An {@link ApplicationContextRunner} rather than {@code @SpringBootTest}, for the reason
 * {@code CspPropertiesTest} gives: a context that must NOT start cannot be asserted on by an
 * annotation that starts it.
 */
class ContentSecurityPolicyOverrideTest {

    /** A copy of the Cloud header, which is the value an operator actually pastes. */
    private static final String CLOUD_SHAPED_OVERRIDE =
            "app.csp.policy=default-src 'self'; img-src 'self' data:; "
            + "report-uri /api/security/csp-report";

    private final ApplicationContextRunner runner = new ApplicationContextRunner()
            .withConfiguration(org.springframework.boot.autoconfigure.AutoConfigurations
                    .of(ConfigurationPropertiesAutoConfiguration.class))
            .withUserConfiguration(TestConfig.class);

    @Test
    void anOverrideNamingOurOwnReportPathWithTheSinkOffRefusesToStart() {
        runner.withPropertyValues(CLOUD_SHAPED_OVERRIDE, "app.csp.sink-enabled=false")
                .run(context -> {
                    assertThat(context)
                            .as("""
                                THE HEADER MAY NOT NAME A PATH THIS INSTANCE DOES NOT SERVE.

                                If this boots, a DC box emits a report-uri for an endpoint that is \
                                not registered, and every violation a browser sees becomes a POST \
                                answered 405 - an unauthenticated request storm generated by our \
                                own header, which is the exact failure five comments in this \
                                feature say is impossible by construction.""")
                            .hasFailed();
                    assertThat(context.getStartupFailure())
                            .rootCause()
                            .as("""
                                A REFUSAL MUST NAME AN ACTION ITS READER CAN PERFORM.

                                The reader is holding two variables and either one resolves this: \
                                serve the sink, or drop the clause. A message that only says the \
                                policy is wrong sends them back to the policy, which is the half \
                                they copied on purpose.""")
                            .isInstanceOf(IllegalStateException.class)
                            .hasMessageContaining("CSP_REPORT_SINK_ENABLED")
                            .hasMessageContaining("CSP_POLICY");
                });
    }

    /** The same override, with the half that makes it honest. */
    @Test
    void theSameOverrideBootsWhenTheInstanceActuallyServesTheSink() {
        runner.withPropertyValues(CLOUD_SHAPED_OVERRIDE, "app.csp.sink-enabled=true")
                .run(context -> {
                    assertThat(context).hasNotFailed();
                    assertThat(context.getBean(ContentSecurityPolicy.class).headerValue())
                            .as("an override is emitted verbatim — the built-in clause is not "
                                + "appended to it, and nothing here rewrites an operator's string")
                            .isEqualTo("default-src 'self'; img-src 'self' data:; "
                                       + "report-uri /api/security/csp-report");
                });
    }

    /**
     * <strong>The check is scoped to this instance's own path, not to the words
     * {@code report-uri}.</strong> Sending violations to a collector outside this instance is a
     * legitimate thing for an operator to configure — it is most of why the override exists — and
     * nothing here is entitled to refuse it. A guard that read the directive name instead of the
     * path would ban that with no notice and no way to ask.
     */
    @Test
    void anOverrideNamingSomebodyElsesCollectorIsNoneOfThisGuardsBusiness() {
        runner.withPropertyValues(
                        "app.csp.policy=default-src 'self'; report-uri https://csp.example/collect",
                        "app.csp.sink-enabled=false")
                .run(context -> {
                    assertThat(context).hasNotFailed();
                    assertThat(context.getBean(ContentSecurityPolicy.class).headerValue())
                            .contains("https://csp.example/collect");
                });
    }

    /**
     * With the header off entirely there is no policy on the wire, so there is no clause to
     * dishonour and nothing to refuse. Asserted rather than left to reading, because the natural
     * "validate the property wherever it is bound" implementation would abort a boot over a header
     * the instance does not send.
     */
    @Test
    void theGuardDoesNotFireWhenNoHeaderIsSentAtAll() {
        runner.withPropertyValues(CLOUD_SHAPED_OVERRIDE, "app.csp.sink-enabled=false",
                        "app.csp.report-only-enabled=false")
                .run(context -> {
                    assertThat(context).hasNotFailed();
                    assertThat(context.getBean(ContentSecurityPolicy.class).headerValue()).isNull();
                });
    }

    /**
     * <strong>The refusal is about the TARGET of a report-uri, and the first version of it was a
     * substring test that got the category wrong in both directions.</strong>
     *
     * <p>Over-broad where it costs most: the collector a fleet operator points DC boxes at is,
     * obviously, another Hamstrack — so its URL contains our path, and the box refused to boot
     * while telling its operator to do two things neither of which was theirs to do.
     */
    @Test
    void aCentralHamstrackCollectorIsNotThisGuardsBusinessEvenThoughItsUrlContainsOurPath() {
        runner.withPropertyValues(
                        "app.csp.policy=default-src 'self'; "
                        + "report-uri https://collect.example.com/api/security/csp-report",
                        "app.csp.sink-enabled=false")
                .run(context -> assertThat(context)
                        .as("""
                            A REFUSAL MAY ONLY PRESCRIBE AN ACTION ITS READER CAN PERFORM.

                            This operator runs a fleet of self-hosted boxes reporting to one \
                            central instance, and the obvious collector to name is another \
                            Hamstrack - whose URL contains our own path by construction. Refusing \
                            here bricks the boot and offers two remedies, neither of which is \
                            theirs: turning on an unauthenticated endpoint they did not ask for \
                            does not change where the reports go, and dropping the clause deletes \
                            the collection they configured on purpose.""")
                        .hasNotFailed());
    }

    /** The same URL, on this instance's own host, is squarely this guard's business. */
    @Test
    void anAbsoluteReportUriOnThisInstancesOwnHostIsCheckedLikeARelativeOne() {
        runner.withPropertyValues(
                        "app.csp.policy=default-src 'self'; "
                        + "report-uri https://tracker.example.com/api/security/csp-report",
                        "app.csp.sink-enabled=false")
                .run(context -> assertThat(context)
                        .as("app.base-url names tracker.example.com, so this clause aims every "
                            + "browser at a path THIS instance does not serve")
                        .hasFailed());
    }

    /**
     * <strong>The three spellings a {@code contains} test never saw.</strong> Each produces exactly
     * the storm the guard exists to prevent, and each was silent: Spring matches paths
     * case-sensitively, so {@code /API/SECURITY/CSP-REPORT} is served by nothing; Boot does not
     * match a trailing slash, and the substring branch only ever fired with the sink <em>off</em>,
     * so that spelling passed on precisely the instance that thought it was collecting; and Tomcat
     * decodes before mapping, so {@code csp%2Dreport} <em>is</em> the sink's path wearing a
     * disguise the substring could not see through.
     */
    @Test
    void aReportUriAimedHereThatNoMappingServesRefusesWhateverTheSinkSaysAboutItself() {
        for (var spelling : new String[]{
                "/API/SECURITY/CSP-REPORT",
                "/api/security/csp-report/",
                "/api/security/csp-reports"}) {
            runner.withPropertyValues("app.csp.policy=default-src 'self'; report-uri " + spelling,
                            "app.csp.sink-enabled=true")
                    .run(context -> assertThat(context)
                            .as("""
                                A PATH AIMED AT THIS INSTANCE THAT THIS INSTANCE DOES NOT SERVE \
                                IS THE SAME FAILURE AS THE SINK BEING OFF, AND WAS NOT REFUSED: \
                                %s.

                                The guard tested whether the policy string CONTAINED our path, so \
                                every spelling that is not byte-identical to it walked past - \
                                while the browser posts to a path answered by 405 either way. \
                                Decide on the target, not on a substring.""".formatted(spelling))
                            .hasFailed());
        }
    }

    /**
     * And the encoded spelling of the path we DO serve is treated as the path we serve — refused
     * with the sink off, accepted with it on. {@code URI.getPath()} decodes, which is the same
     * thing Tomcat does before it maps.
     */
    @Test
    void aPercentEncodedSpellingOfOurOwnPathIsResolvedRatherThanCompared() {
        runner.withPropertyValues(
                        "app.csp.policy=default-src 'self'; "
                        + "report-uri /api/security/csp%2Dreport",
                        "app.csp.sink-enabled=false")
                .run(context -> assertThat(context)
                        .as("this IS our path — Tomcat decodes before mapping — so with the sink "
                            + "off it is the exact failure the guard exists for, and `contains` "
                            + "did not see it")
                        .hasFailed());

        runner.withPropertyValues(
                        "app.csp.policy=default-src 'self'; "
                        + "report-uri /api/security/csp%2Dreport",
                        "app.csp.sink-enabled=true")
                .run(context -> assertThat(context)
                        .as("and with the sink on it names a path that is served, so there is "
                            + "nothing to refuse")
                        .hasNotFailed());
    }

    /**
     * <strong>And the encoded spelling that decodes to our path but is refused by the container is
     * refused here too — the mirror of the case above.</strong>
     *
     * <p>{@code %2D} was "the guard refuses, the server serves". {@code %2F} is "the guard permits,
     * the server refuses": {@code URI.getPath()} decodes {@code /api/security%2Fcsp-report} to
     * exactly {@code REPORT_PATH}, so a check that reads only the decoded path lets it boot — and
     * then Tomcat answers {@code 400} to every report a browser posts, which is the same
     * unauthenticated storm generated by our own header that this guard exists to prevent. Refused
     * with the sink <em>on</em>, deliberately: the sink's state has nothing to do with it, and the
     * instance that thinks it is collecting is the one this failure is invisible on.
     */
    @Test
    void aPathSpelledWithAnEncodedSlashIsRefusedEvenThoughItDecodesToOurOwn() {
        runner.withPropertyValues(
                        "app.csp.policy=default-src 'self'; "
                        + "report-uri /api/security%2Fcsp-report",
                        "app.csp.sink-enabled=true")
                .run(context -> {
                    assertThat(context)
                            .as("""
                                A DECODER DISAGREEMENT RUNS BOTH WAYS, AND ONLY ONE DIRECTION WAS \
                                CLOSED.

                                getPath() decodes %2F to a slash, so this token IS our path as far \
                                as the guard can see - but Tomcat rejects an encoded slash in a \
                                path with 400 before any mapping is consulted. The guard permits, \
                                the server refuses, and every violation a browser sees becomes a \
                                400. Consult the raw path as well as the decoded one.""")
                            .hasFailed();
                    assertThat(context.getStartupFailure())
                            .rootCause()
                            .hasMessageContaining("%2F");
                });
    }

    @Configuration(proxyBeanMethods = false)
    @EnableConfigurationProperties(CspProperties.class)
    static class TestConfig {
        @Bean
        ContentSecurityPolicy contentSecurityPolicy(CspProperties properties) {
            // Only baseUrl is read: it is what decides whether an absolute report-uri is aimed at
            // this instance or at somebody else's collector.
            return new ContentSecurityPolicy(properties, new AppProperties(
                    "https://tracker.example.com", null, null, null, null, null, null));
        }
    }
}
