package com.hamstrack.common.config;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.bind.DefaultValue;
import org.springframework.validation.annotation.Validated;

/**
 * The Content-Security-Policy an operator can see and, in one case, replace (HD-264,
 * {@code docs/design/content-security-policy-proposal.md} §12).
 *
 * <p><strong>Report-only, in this release and in every configuration of it.</strong> There is no
 * property here that makes the policy enforcing, deliberately and not as an omission: the ticket's
 * own acceptance criterion is that the enforcement decision cites evidence rather than a guess, and
 * a flag that "just flips it on later" is how the evidence step gets skipped under release
 * pressure. The enforcing header is written by the enforcement ticket, which cites §7 of the
 * proposal.
 *
 * <p><strong>{@code @Validated} because a component below declares a constraint</strong>, which on
 * a {@code @ConfigurationProperties} class is the only thing that makes a declared constraint fire
 * at all — binding happens once at startup and nothing is dispatched to. It is the
 * {@link AppProperties} / {@link SearchProperties} pattern and the opposite of ADR-0018's rule for
 * web beans, which is why {@code CspReportController} carries no such annotation.
 *
 * <p><strong>Exactly one value here is profile-defaulted, and it is {@link #sinkEnabled()}.</strong>
 * The default lives in {@code application-dc.properties} / {@code application-cloud.properties}, in
 * the shape {@code app.storage.type} and {@code app.registration.public-signup-enabled} already
 * use; no code anywhere asks which profile it is running under. The header itself is identical in
 * both modes but for the {@code report-uri} clause, and that clause is a function of this property
 * rather than of the profile — see {@code ContentSecurityPolicy}.
 */
@Validated
@ConfigurationProperties(prefix = "app.csp")
public record CspProperties(
        /*
         * Whether the Content-Security-Policy-Report-Only header is emitted at all. On in BOTH
         * modes (owner decision D2): a report-only header with no report-uri still writes
         * violations to the browser console, costs ~280 bytes, cannot block anything, and means a
         * self-hoster reporting "my board looks odd" already has the evidence on their screen. A
         * header only Cloud gets would be a behavioural fork by profile for no benefit, and would
         * make DC the mode where the policy has never been observed.
         */
        @DefaultValue("true") boolean reportOnlyEnabled,

        /*
         * Whether POST /api/security/csp-report exists on this instance, AND therefore whether the
         * header names a report-uri. ONE property for both halves, which is what closes the
         * "report-uri that 404s" failure BY CONSTRUCTION rather than by care: there is no
         * configuration in which the header names an endpoint the instance does not serve. Had the
         * clause been unconditional, every violation on a DC box would POST to a path /api/** answers
         * 401 on - an unauthenticated request storm generated by our own header.
         *
         * ONE property decides both halves OF THE BUILT-IN POLICY, which is why the policy override
         * below is not free to disagree with it: an override replaces the directive string
         * wholesale and would otherwise reintroduce exactly this failure - most likely by somebody
         * copying an observed Cloud header onto a DC box. ContentSecurityPolicy REFUSES THE BOOT on
         * an override that names this instance's own report path while this is false, which is what
         * keeps "by construction" a construction rather than a sentence.
         *
         * Default false here and true only on the cloud profile, for two reasons that are both
         * about the self-hoster: it is an unauthenticated public endpoint, and nobody should be
         * given one by an upgrade they did not ask for; and the per-IP budget needs a real client
         * IP, while RATE_LIMIT_TRUST_FORWARDED_FOR defaults to false on DC (correctly - the app
         * port may be directly reachable), so behind a proxy every report would arrive from one
         * address and the per-IP bound would degrade to the instance bound. docs/self-hosting.md
         * documents the two together for that reason.
         */
        @DefaultValue("false") boolean sinkEnabled,

        /*
         * A full replacement for the built-in directive string, or empty to use it. Empty on both
         * profiles: the built-in policy contains no deployment-specific value at all - every source
         * is 'self', 'none', data: or one of two absolute font origins - which is what makes one
         * version-controlled string correct for Cloud and for every self-hosted install at once.
         *
         * THE CONSTRAINTS ARE A RESPONSE-SPLITTING GUARD AND NOT A SYNTAX CHECK. A CSP that is
         * syntactically broken is ignored by browsers directive-by-directive and costs an operator
         * nothing they cannot see; a value carrying CR or LF would let an operator's typo split
         * every response this instance writes. So the character class admits printable ASCII only
         * (space through tilde), which is every character a CSP directive can contain and no
         * control character, and a bad value FAILS STARTUP rather than shipping. The length bound
         * is the same kind of belt: a header this instance emits on every response is not a place
         * to discover that somebody pasted a file into an environment variable.
         */
        @DefaultValue("")
        @Size(max = 2000, message = TOO_LONG)
        @Pattern(regexp = PRINTABLE_ASCII, message = NOT_A_HEADER_VALUE)
        String policy,

        /*
         * How many LOG LINES one IP may buy per minute. The unit is the line and not the request,
         * because a request may carry a batch: the guard filter spends one token to admit a
         * request (which pays for its first line) and CspReportSink spends one more for every
         * further line that request writes. Counted per request, the same number would have meant
         * up to 20x as many lines - a bound on requests is not a bound on volume, and every figure
         * below is stated in the unit a reader can check.
         *
         * Derivation: a worst-case document in which EVERY subresource is refused produces at most
         * 22 reports (20 built asset files + 2 external font origins), so 60/min leaves ~3x
         * headroom over a client hard-navigating twice a minute. What it costs the instance: one
         * line is at most ~700 bytes of field values, ~1.2 KB on the wire with the field names and
         * the logstash envelope - so ~70 KB a minute, about 100 MB a day, from any one address.
         *
         * ITS OWN POT, AND IN PARTICULAR NOT app.rate-limit.auth-ip-requests-per-minute. A report
         * flood must never be able to lock a user out of /login: that budget is per-IP, shared IPs
         * are ordinary, and this handler's work is one log line and one counter increment. A
         * throttle is earned by the work a handler does.
         */
        @DefaultValue("60") @Min(1) @Max(10_000) int reportsPerMinutePerIp,

        /*
         * The instance-wide ceiling, 10x the per-IP one: a sink hearing from ten simultaneously
         * violating clients has already told the operator everything it can, and must not become
         * the instance's log budget. In the same unit: 600 lines a minute is ~700 KB a minute,
         * about 1 GB a day if it is saturated every minute of every day.
         */
        @DefaultValue("600") @Min(1) @Max(100_000) int reportsPerMinute
) {

    /** Space through tilde: every character a CSP directive uses, and no control character. */
    private static final String PRINTABLE_ASCII = "[ -~]*";

    private static final String NOT_A_HEADER_VALUE =
            "must contain printable ASCII only. CSP_POLICY is written verbatim into a response "
            + "header on every response this instance serves, so a carriage return or a line feed "
            + "in it splits the response rather than breaking the policy. Leave it empty to use "
            + "the built-in policy";

    private static final String TOO_LONG =
            "must be at most 2000 characters. CSP_POLICY is emitted on every response; the "
            + "built-in policy is about 320. Leave it empty to use the built-in one";

    /**
     * A blank override is the same thing as an absent one — {@code CSP_POLICY=} in an env file is
     * how "I do not want to override it" is spelled, and a whitespace-only value is a typo rather
     * than a policy. Runs before validation, so a stripped value is what the constraints see.
     */
    public CspProperties {
        policy = policy == null ? "" : policy.strip();
    }
}
