// HD-186 load harness — pre-flight token minting.
// Spec: §4.4(2), §5.2 (pre-flight phase).
//
//   export LOAD_PASSWORD='…'        # k6 inherits the environment; never pass it as -e,
//   k6 run k6/mint-tokens.js \      # which puts a credential in `ps` output
//     -e BASE_URL=http://origin:8080 -e ACCOUNTS=120
//
// Writes tokens.json, which every mix loads. Takes about fifteen minutes for 135 accounts
// and doubles as a smoke test — if the instance cannot serve 135 sequential logins, the
// window is over before it opened.
//
// ---------------------------------------------------------------------------
// WHY THIS IS SLOW ON PURPOSE.
//
// /api/auth/login is in the auth filter's URL set at RATE_LIMIT_AUTH_IP_PER_MINUTE
// (15/min), keyed on the peer address — and where RATE_LIMIT_TRUST_FORWARDED_FOR is on,
// on the rightmost X-Forwarded-For. Every login here comes from ONE generator address, so
// the whole fleet shares one 15/minute bucket.
//
// This throttles ITSELF to 10 logins per minute, client-side, with two thirds of the
// budget spare. RAISING THE LIMITER FOR THE WINDOW IS REJECTED: it changes the
// configuration under measurement, and the limiters' behaviour is a RESULT of this run,
// not an obstacle to it. A harness that turns off the thing being measured measures
// nothing.
//
// The spare third is not caution for its own sake. Real users log in during the window
// (the site stays live, §11 Q2), and a minting phase that consumed the entire per-IP
// budget would lock them out — turning a measurement into an outage for the handful of
// people the run is supposed to be measured around.
//
// ---------------------------------------------------------------------------
// THREE POOLS, ASKED FOR BY ADDRESS FAMILY. A CORRECTNESS PROPERTY, NOT TIDINESS.
//
//   accountsA       load-a-NNN   workspace-A members. THE LOAD.
//   accountsCanary  load-ac-NNN  workspace-A members reserved for the tenancy canary.
//   accountsB       load-b-NNN   workspace-B members. Never load; the canary's TARGET.
//
// Emitting these as one flat list made a VU's principal a function of its index, and at two
// shipped configurations the canary's own VU landed on a MEMBER of workspace B, which then
// received a correct 200 from a correct server and aborted the window as a security
// incident. Quieter and worse: from 60 VUs up, a slice of the browsing fleet held B
// credentials while driving A's paths, so every one of those requests 404'd cheaply and was
// averaged into the browse latency the breach point is read from.
//
// Splitting A from B fixed that half and left the other: the canary was then pinned to
// accountsA[0] — AN INDEX INSIDE THE RANGE THE LOAD DRAWS FROM. One load VU held the same
// account, and /api/auth/refresh ROTATES, so whichever of the two spent the single-use
// refresh token first left the other unable to authenticate. The canary then read that 400
// as "expected 404" and declared a security incident against a correct server.
//
// So the canary's principals are their own ADDRESS FAMILY, generated by the fixture as
// load-ac-NNN (fixture/10-generate.sql section 1) and asked for here BY NAME. No index
// arithmetic connects the three arrays, which is what makes them disjoint by construction
// rather than by a bound somebody has to keep re-checking.
//
// ---------------------------------------------------------------------------
// HOW MANY: ENOUGH FOR THE PEAK VU COUNT, WHICH IS NOT THE HEADLINE VU COUNT.
//
// lib/auth.js maps VU -> principal injectively (accountsA[__VU - 1], no modulo), so the A
// pool must cover every VU k6 ALLOCATES. The browse mix declares three scenarios (browse at
// VUS, sse at VUS, canary at 1), so its 100-VU stage instantiates 201 VUs. 210 is that,
// rounded up. Both run-ladder.sh (from `k6 inspect --execution-requirements`) and each
// mix's setup() (from the resolved options) REFUSE rather than warn when it is short.

import http from 'k6/http';
import { sleep } from 'k6';
import { BASE_URL, HOST_HEADER, SYSTEM_TAGS } from './lib/config.js';

const PASSWORD = __ENV.LOAD_PASSWORD;
if (!PASSWORD) throw new Error('LOAD_PASSWORD is required (export it; do not pass -e)');

// The floor is checked HERE as well as in fixture/verify-api.sh because these are the two
// places the plaintext first arrives, one per machine, and a password chosen by a human is
// what this replaced. 135 accounts on production share it and they outlive an aborted
// window (fixture/revoke.sh is what ends them). Generate it: `openssl rand -base64 24`.
const MIN_PASSWORD_LEN = 24;
if (PASSWORD.length < MIN_PASSWORD_LEN) {
  throw new Error(`LOAD_PASSWORD is ${PASSWORD.length} characters; the floor is ` +
    `${MIN_PASSWORD_LEN}. Do not choose one — generate it: openssl rand -base64 24`);
}

// 210: the browse mix's peak at the ladder's 100-VU top stage is 2x100 + 1 = 201 VUs, and
// every one of them needs its own principal. The fixture must actually hold this many
// workspace-A load accounts — fixture/10-generate.sql section 1 is the other half of this
// number, and changing one without the other fails at the first login.
const COUNT_A = Number(__ENV.ACCOUNTS || 210);
const COUNT_CANARY = Number(__ENV.ACCOUNTS_CANARY || 2);
const COUNT_B = Number(__ENV.ACCOUNTS_B || 15);
const PER_MINUTE = Number(__ENV.LOGINS_PER_MINUTE || 10);
const GAP = 60 / PER_MINUTE;

export const options = {
  // THE WORK HAPPENS IN setup(), AND THAT IS NOT A STYLE CHOICE.
  //
  // handleSummary() is the ONLY place a k6 script may write a file, and it runs in its own
  // context: it does NOT see module-scope variables or globalThis assigned by the default
  // function. This script used to stash its result in `globalThis.__mintResult` and read it
  // back in handleSummary, which returns `undefined` there — so it wrote a tokens.json
  // containing zero accounts, printed "wrote … 0 A + 0 B accounts", and exited 0. Every mix
  // then refused to start on "tokens.json has no accountsA", which reads like a minting
  // failure and is really a plumbing one.
  //
  // handleSummary DOES receive `data.setup_data` — setup()'s return value, serialised by k6
  // — so setup() mints and handleSummary writes what it returned. The default function is a
  // formality k6 requires.
  //
  // setupTimeout is the other half: it defaults to SIXTY SECONDS, and minting the shipped
  // pool takes about twenty-three minutes at the per-IP limiter's pace.
  setupTimeout: '90m',
  scenarios: {
    mint: { executor: 'per-vu-iterations', vus: 1, iterations: 1, maxDuration: '5m' },
  },
  // No latency thresholds here. This phase runs BEFORE the measured window and its
  // timings describe a deliberately throttled client, not the instance.
  thresholds: {},
  // `url` is dropped, in EVERY script, including this one. No request here carries a
  // credential in its query string today — which is exactly why this was the one file
  // without the line. The tag set is a property of the harness's OUTPUT, not of one
  // request: this script's run can be recorded with --out like any other, and the next
  // request added to it will not be audited for a list it never had.
  systemTags: SYSTEM_TAGS,
};

// The three address families the fixture generates. Asked for BY NAME — no offset, no
// slice, no "the last two of A". A family is something the fixture either has or has not;
// an index is something that quietly means a different account after somebody edits a count.
function emails(prefix, count) {
  const out = [];
  for (let i = 1; i <= count; i++) {
    out.push(`${prefix}-${String(i).padStart(3, '0')}@load.invalid`);
  }
  return out;
}

/** One throttled login. Returns an account record, or null (and records the failure). */
function mintOne(email, failures) {
  const headers = { 'Content-Type': 'application/json' };
  if (HOST_HEADER) headers.Host = HOST_HEADER;

  const res = http.post(`${BASE_URL}/api/auth/login`,
    JSON.stringify({ email: email, password: PASSWORD }),
    { headers: headers, tags: { class: 'auth', op: 'mint' } });

  if (res.status === 429) {
    // The client-side throttle is meant to make this unreachable. Reaching it means
    // something else is logging in from this address, or the limiter is configured
    // lower than the harness believes — either way the fingerprint is wrong and the run
    // record must say so. Back off a full window; the caller retries.
    console.warn(`429 minting ${email} — the per-IP auth budget is tighter than assumed ` +
      `or shared. Backing off 60s. RECORD THIS: the limiter configuration in the ` +
      `fingerprint (§4.9) does not match observed behaviour.`);
    sleep(60);
    return undefined;       // undefined = retry me; null = give up on this account
  }

  if (res.status !== 200) {
    failures.push({ email: email, status: res.status });
    console.error(`login failed for ${email}: HTTP ${res.status} ` +
      `${String(res.body).slice(0, 200)}`);
    sleep(GAP);
    return null;
  }

  const body = JSON.parse(res.body);
  // The refresh cookie is single-use: /api/auth/refresh ROTATES (deletes the presented
  // token, issues a new one). Captured here and replayed into each VU's jar; from then
  // on the chain lives inside the k6 process that owns it.
  const jar = http.cookieJar();
  const cookies = jar.cookiesForURL(`${BASE_URL}/api/auth/refresh`);
  const refresh = cookies.refresh_token ? cookies.refresh_token[0] : null;
  if (!refresh) {
    console.warn(`no refresh_token cookie for ${email} — this VU will be unable to ` +
      `refresh and will fail loudly ~30 minutes in`);
  }
  // Clear the jar so the NEXT login does not present this account's cookie and get it
  // rotated out from under the account that owns it.
  jar.clear(`${BASE_URL}/api/auth`);

  sleep(GAP);
  return {
    email: email,
    userId: body.userId,
    accessToken: body.accessToken,
    refreshToken: refresh,
    expiresIn: body.expiresIn,
  };
}

function mintAll(list, failures, label) {
  const out = [];
  for (let i = 0; i < list.length; i++) {
    let acct = mintOne(list[i], failures);
    if (acct === undefined) acct = mintOne(list[i], failures);   // one retry after a 429
    if (acct) out.push(acct);
    if ((i + 1) % 10 === 0) console.log(`  ${label} ${i + 1}/${list.length}`);
  }
  return out;
}

export function setup() {
  const listA = emails('load-a', COUNT_A);
  const listC = emails('load-ac', COUNT_CANARY);
  const listB = emails('load-b', COUNT_B);
  const failures = [];
  const total = listA.length + listC.length + listB.length;

  console.log(`minting ${listA.length} A + ${listC.length} canary + ${listB.length} B ` +
    `tokens at ${PER_MINUTE}/min (~${Math.ceil((total * GAP) / 60)} minutes) against ${BASE_URL}`);

  const accountsA = mintAll(listA, failures, 'A');
  const accountsCanary = mintAll(listC, failures, 'canary');
  const accountsB = mintAll(listB, failures, 'B');

  if (failures.length) {
    console.error(`${failures.length} account(s) failed to authenticate. Pool A is ` +
      `${accountsA.length}; if that is below the ladder's top stage, VUs will share ` +
      `principals and the per-principal budgets will bind early (§4.4).`);
  }
  if (!accountsCanary.length) {
    console.error('THE CANARY POOL IS EMPTY. Its principals are the load-ac-NNN family and ' +
      'the fixture generates them (10-generate.sql section 1). Without them the canary has ' +
      'to borrow a load principal — the defect this pool exists to remove, because a shared ' +
      'account has one single-use refresh token and two holders. Every mix will refuse to ' +
      'start.');
  }
  if (!accountsB.length) {
    console.error('POOL B IS EMPTY. The tenancy canary needs a workspace-B principal to ' +
      'prove its target EXISTS; without one it cannot distinguish "the server refused" ' +
      'from "the harness pointed at nothing", and every mix will refuse to start.');
  }

  const out = {
    mintedAt: new Date().toISOString(),
    baseUrl: BASE_URL,
    accessTokenLifetimeSeconds: accountsA.length ? accountsA[0].expiresIn : null,
    poolSize: accountsA.length,
    canaryPoolSize: accountsCanary.length,
    foreignPoolSize: accountsB.length,
    failures: failures,
    // THREE arrays, never one and never two. See the header. `mintedAt` and
    // `accessTokenLifetimeSeconds` above are not decoration either: run-ladder.sh reads them
    // and refuses to start a stage that would run past the expiry, because the refresh
    // tokens below are SINGLE-USE and a second k6 process presenting the same string gets a
    // 400 from a server that is behaving correctly.
    accountsA: accountsA,
    accountsCanary: accountsCanary,
    accountsB: accountsB,
  };
  console.log(`minted ${accountsA.length} A + ${accountsCanary.length} canary + ` +
    `${accountsB.length} B tokens`);
  // RETURNED, not stashed. handleSummary reads it as data.setup_data; a module-scope or
  // globalThis assignment made here is invisible there. See the note on options above.
  return out;
}

// k6 requires an exec target for the scenario. There is nothing to do per iteration: the
// whole job is setup()'s, because that is the only result handleSummary can see.
export default function () {}

export function handleSummary(data) {
  const out = (data && data.setup_data) || { accountsA: [], accountsCanary: [], accountsB: [] };
  const n = (out.accountsA || []).length + (out.accountsCanary || []).length +
            (out.accountsB || []).length;
  // ABSOLUTE, AND REQUIRED. handleSummary's keys resolve against the WORKING DIRECTORY while
  // lib/auth.js's open() resolves against the SCRIPT, so the two ends of the same name have
  // two different bases: a bare 'tokens.json' minted from the harness root landed one
  // directory above the file run-ladder.sh then told k6 to read. A default that is right
  // from one working directory and wrong from another is not a default, it is a trap — so
  // there is none. It also keeps this credential file out of the synced ops/ tree by making
  // its location a decision somebody has to write down (config.env.example).
  const dest = __ENV.TOKENS_FILE;
  if (!dest || (dest[0] !== '/' && !/^[A-Za-z]:[\\/]/.test(dest))) {
    throw new Error('TOKENS_FILE must be set to an ABSOLUTE path. It is a credential file ' +
      'for ' + n + ' accounts; its two readers resolve relative paths against different ' +
      'bases, and its home belongs outside the synced ops/ tree. ' +
      'Example: TOKENS_FILE=/var/tmp/hd186/tokens.json');
  }
  if (n === 0) {
    // Refuse to overwrite a working tokens.json with an empty one. This is the exact shape
    // of the defect that made this script silently useless: an empty result written
    // confidently, with an exit code of 0.
    throw new Error('minted 0 accounts, so ' + dest + ' has NOT been written. Read the ' +
      'login failures above. If there are none, setup() did not run — check setupTimeout.');
  }
  const summary = {};
  summary[dest] = JSON.stringify(out, null, 2);
  return Object.assign(summary, {
    stdout: `\n  wrote ${dest} — ${(out.accountsA || []).length} A + ` +
      `${(out.accountsCanary || []).length} canary + ${(out.accountsB || []).length} B accounts\n` +
      `  Access tokens expire in ${out.accessTokenLifetimeSeconds}s, from mintedAt=${out.mintedAt}.\n` +
      `  THE REFRESH TOKENS IN THIS FILE ARE SINGLE-USE: /api/auth/refresh ROTATES, so each\n` +
      `  string can be spent exactly once, ever, by exactly one holder. A ladder is a\n` +
      `  SEQUENCE OF k6 PROCESSES all seeded from this one file, so the first stage that\n` +
      `  crosses the expiry spends it for every account and every later stage then presents\n` +
      `  a token the server has already deleted. run-ladder.sh REFUSES to start such a\n` +
      `  stage; k6/refresh-tokens.js advances the whole file's chain in about a minute,\n` +
      `  which is what to run between stages instead of re-minting for twenty.\n\n` +
      `  tokens.json IS A CREDENTIAL FILE for ${n} accounts, and DESTROYING IT REVOKES\n` +
      `  NOTHING. It is the client's copy: the refresh tokens in it live 30 days on the\n` +
      `  server (jwt.refresh-token-expiration=P30D) and the accounts keep working with the\n` +
      `  shared password whatever happens to this file or to the machine holding it.\n` +
      `  Terminating the generator is housekeeping, not revocation.\n\n` +
      `  THE ONLY THING THAT REVOKES IS THE SERVER: ops/loadtest/fixture/revoke.sh, run on\n` +
      `  the box. It is the FIRST step of the abort path, before any teardown.\n\n`,
  });
}
