-- =============================================================================
-- Hamstrack — Initial Schema (Phase 1-3)
-- IDs: UUID v7 (generated by the application layer via Hibernate @UuidGenerator)
-- Timestamps: managed by application (@CreationTimestamp / @UpdateTimestamp)
--             DEFAULT NOW() serves as a safety net for raw SQL operations
-- updated_at triggers: keep data consistent even when modified outside JPA
-- =============================================================================

-- ---------------------------------------------------------------------------
-- ENUMS
-- ---------------------------------------------------------------------------

-- Enum values are enforced at the application layer (Java enums + Bean Validation).
-- VARCHAR avoids JDBC/Hibernate type-casting friction with PostgreSQL custom ENUM types.

-- ---------------------------------------------------------------------------
-- SHARED TRIGGER — keeps updated_at accurate for raw-SQL writes outside JPA
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- AUTH & USERS
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            UUID          PRIMARY KEY,
    email         VARCHAR(255)  NOT NULL UNIQUE,
    display_name  VARCHAR(100)  NOT NULL,
    avatar_url    TEXT,
    password_hash VARCHAR(255),                          -- NULL for OAuth-only accounts
    status        VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- OAuth 2.0 linked accounts (Google, GitHub, …)
CREATE TABLE oauth_accounts (
    id               UUID         PRIMARY KEY,
    user_id          UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider         VARCHAR(50)  NOT NULL,              -- 'google', 'github'
    provider_user_id VARCHAR(255) NOT NULL,
    access_token     TEXT,
    refresh_token    TEXT,
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE(provider, provider_user_id)
);

-- JWT refresh tokens — SHA-256 hash stored, never the raw token
CREATE TABLE refresh_tokens (
    id         UUID        PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Email verification flow
CREATE TABLE email_verifications (
    id          UUID        PRIMARY KEY,
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    verified_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Password reset flow
CREATE TABLE password_resets (
    id         UUID        PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- WORKSPACES (tenant boundary)
-- ---------------------------------------------------------------------------

CREATE TABLE workspaces (
    id         UUID         PRIMARY KEY,
    slug       VARCHAR(100) NOT NULL UNIQUE,             -- URL-safe identifier
    name       VARCHAR(255) NOT NULL,
    created_by UUID         NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_workspaces_updated_at
    BEFORE UPDATE ON workspaces
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE workspace_members (
    id           UUID           PRIMARY KEY,
    workspace_id UUID           NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_id      UUID           NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role         VARCHAR(20)    NOT NULL DEFAULT 'MEMBER',
    joined_at    TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    UNIQUE(workspace_id, user_id)
);

CREATE TABLE workspace_invites (
    id           UUID           PRIMARY KEY,
    workspace_id UUID           NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    email        VARCHAR(255)   NOT NULL,
    role         VARCHAR(20)    NOT NULL DEFAULT 'MEMBER',
    token_hash   VARCHAR(64)    NOT NULL UNIQUE,
    invited_by   UUID           NOT NULL REFERENCES users(id),
    expires_at   TIMESTAMPTZ    NOT NULL,
    accepted_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- PROJECTS
-- ---------------------------------------------------------------------------

CREATE TABLE projects (
    id          UUID        PRIMARY KEY,
    workspace_id UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    key         VARCHAR(10)  NOT NULL,                  -- e.g. "PROJ", "HMS"
    description TEXT,
    archived_at TIMESTAMPTZ,
    issue_seq   BIGINT       NOT NULL DEFAULT 0,        -- atomic counter for issue numbers
    created_by  UUID         NOT NULL REFERENCES users(id),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE(workspace_id, key)
);

CREATE TRIGGER trg_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE project_members (
    id         UUID         PRIMARY KEY,
    project_id UUID         NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id    UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    joined_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE(project_id, user_id)
);

-- ---------------------------------------------------------------------------
-- ISSUE TAXONOMY (workspace-level, shared across projects)
-- ---------------------------------------------------------------------------

CREATE TABLE issue_types (
    id           UUID        PRIMARY KEY,
    workspace_id UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name         VARCHAR(100) NOT NULL,
    color        CHAR(7)      NOT NULL DEFAULT '#6B7280', -- hex: #RRGGBB
    icon         VARCHAR(50),
    position     SMALLINT     NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE(workspace_id, name)
);

CREATE TABLE statuses (
    id           UUID            PRIMARY KEY,
    workspace_id UUID            NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name         VARCHAR(100)    NOT NULL,
    color        CHAR(7)         NOT NULL DEFAULT '#6B7280',
    category     VARCHAR(20)     NOT NULL,
    position     SMALLINT        NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE(workspace_id, name)
);

-- Workflow: which transitions are allowed between statuses
-- project_id NULL  = workspace-level default (applies to all projects)
-- issue_type_id NULL = applies to all issue types within the workflow
CREATE TABLE workflows (
    id            UUID        PRIMARY KEY,
    workspace_id  UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    project_id    UUID        REFERENCES projects(id) ON DELETE CASCADE,
    issue_type_id UUID        REFERENCES issue_types(id) ON DELETE CASCADE,
    name          VARCHAR(100) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- from_status_id NULL = "any status" (initial/wildcard transition)
CREATE TABLE workflow_transitions (
    id             UUID        PRIMARY KEY,
    workflow_id    UUID        NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
    from_status_id UUID        REFERENCES statuses(id) ON DELETE CASCADE,
    to_status_id   UUID        NOT NULL REFERENCES statuses(id) ON DELETE CASCADE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(workflow_id, from_status_id, to_status_id)
);

-- Which issue types are active in a project
CREATE TABLE project_issue_types (
    id            UUID        PRIMARY KEY,
    project_id    UUID        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    issue_type_id UUID        NOT NULL REFERENCES issue_types(id) ON DELETE CASCADE,
    workflow_id   UUID        REFERENCES workflows(id),
    is_default    BOOLEAN     NOT NULL DEFAULT FALSE,
    position      SMALLINT    NOT NULL DEFAULT 0,
    UNIQUE(project_id, issue_type_id)
);

-- ---------------------------------------------------------------------------
-- BOARDS
-- ---------------------------------------------------------------------------

CREATE TABLE boards (
    id         UUID         PRIMARY KEY,
    project_id UUID         NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name       VARCHAR(100) NOT NULL DEFAULT 'Board',
    type       VARCHAR(20)  NOT NULL DEFAULT 'KANBAN',  -- KANBAN | LIST
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE board_columns (
    id         UUID        PRIMARY KEY,
    board_id   UUID        NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
    status_id  UUID        NOT NULL REFERENCES statuses(id) ON DELETE CASCADE,
    name       VARCHAR(100),                            -- overrides status name if set
    position   SMALLINT    NOT NULL DEFAULT 0,
    wip_limit  SMALLINT    CHECK (wip_limit > 0),      -- NULL = no limit
    UNIQUE(board_id, status_id)
);

-- ---------------------------------------------------------------------------
-- ISSUES
-- ---------------------------------------------------------------------------

CREATE TABLE issues (
    id          UUID           PRIMARY KEY,
    workspace_id UUID           NOT NULL REFERENCES workspaces(id),  -- denormalized for tenant scoping
    project_id  UUID           NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    number      BIGINT         NOT NULL,                             -- project-scoped: PROJECT_KEY-number
    title       VARCHAR(500)   NOT NULL,
    description TEXT,
    type_id     UUID           NOT NULL REFERENCES issue_types(id),
    status_id   UUID           NOT NULL REFERENCES statuses(id),
    priority    VARCHAR(20)    NOT NULL DEFAULT 'NONE',
    assignee_id UUID           REFERENCES users(id),
    reporter_id UUID           NOT NULL REFERENCES users(id),
    parent_id   UUID           REFERENCES issues(id),               -- for sub-tasks
    position    BIGINT         NOT NULL DEFAULT 0,                  -- board ordering; gaps of 1000
    due_date    DATE,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    version     INT            NOT NULL DEFAULT 0,                  -- optimistic locking
    UNIQUE(project_id, number)
);

CREATE TRIGGER trg_issues_updated_at
    BEFORE UPDATE ON issues
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE issue_comments (
    id         UUID        PRIMARY KEY,
    issue_id   UUID        NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    author_id  UUID        NOT NULL REFERENCES users(id),
    body       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ                                          -- soft delete
);

CREATE TRIGGER trg_issue_comments_updated_at
    BEFORE UPDATE ON issue_comments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE issue_history (
    id         UUID         PRIMARY KEY,
    issue_id   UUID         NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    changed_by UUID         NOT NULL REFERENCES users(id),
    field_name VARCHAR(100) NOT NULL,
    old_value  TEXT,
    new_value  TEXT,
    changed_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE issue_attachments (
    id           UUID         PRIMARY KEY,
    issue_id     UUID         NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    filename     VARCHAR(255) NOT NULL,
    storage_key  TEXT         NOT NULL,                             -- path in S3-compatible storage
    size_bytes   BIGINT       NOT NULL CHECK (size_bytes > 0),
    content_type VARCHAR(255) NOT NULL,
    uploaded_by  UUID         NOT NULL REFERENCES users(id),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- NOTIFICATIONS
-- ---------------------------------------------------------------------------

CREATE TABLE notifications (
    id           UUID              PRIMARY KEY,
    user_id      UUID              NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    workspace_id UUID              NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    type         VARCHAR(50)       NOT NULL,
    subject_id   UUID              NOT NULL,                        -- ID of related entity
    subject_type VARCHAR(50)       NOT NULL,                        -- 'issue', 'comment', etc.
    payload      JSONB,                                             -- extra data for rendering
    read_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ       NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------------------------

-- Auth
CREATE INDEX idx_refresh_tokens_user      ON refresh_tokens(user_id);
CREATE INDEX idx_email_verifications_user ON email_verifications(user_id);
CREATE INDEX idx_password_resets_user     ON password_resets(user_id);

-- Workspaces
CREATE INDEX idx_workspace_members_workspace ON workspace_members(workspace_id);
CREATE INDEX idx_workspace_members_user      ON workspace_members(user_id);
CREATE INDEX idx_workspace_invites_workspace ON workspace_invites(workspace_id);
CREATE INDEX idx_workspace_invites_email     ON workspace_invites(email);

-- Projects
CREATE INDEX idx_projects_workspace        ON projects(workspace_id);
CREATE INDEX idx_project_members_project   ON project_members(project_id);
CREATE INDEX idx_project_members_user      ON project_members(user_id);

-- Issue taxonomy
CREATE INDEX idx_issue_types_workspace     ON issue_types(workspace_id);
CREATE INDEX idx_statuses_workspace        ON statuses(workspace_id);
CREATE INDEX idx_workflows_workspace       ON workflows(workspace_id);
CREATE INDEX idx_workflows_project         ON workflows(project_id) WHERE project_id IS NOT NULL;
CREATE INDEX idx_workflow_transitions_wf   ON workflow_transitions(workflow_id);
CREATE INDEX idx_project_issue_types_proj  ON project_issue_types(project_id);

-- Boards
CREATE INDEX idx_board_columns_board       ON board_columns(board_id);

-- Issues
CREATE INDEX idx_issues_project            ON issues(project_id);
CREATE INDEX idx_issues_workspace          ON issues(workspace_id);
CREATE INDEX idx_issues_assignee           ON issues(assignee_id) WHERE assignee_id IS NOT NULL;
CREATE INDEX idx_issues_status             ON issues(status_id);
CREATE INDEX idx_issues_type               ON issues(type_id);
CREATE INDEX idx_issues_parent             ON issues(parent_id)   WHERE parent_id   IS NOT NULL;
CREATE INDEX idx_issues_project_position   ON issues(project_id, position);

-- Issue activity
CREATE INDEX idx_issue_comments_issue      ON issue_comments(issue_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_issue_history_issue       ON issue_history(issue_id);

-- Notifications
CREATE INDEX idx_notifications_user        ON notifications(user_id);
CREATE INDEX idx_notifications_user_unread ON notifications(user_id) WHERE read_at IS NULL;
