-- =============================================================================
-- Hamstrack — consolidated initial schema (baseline)
--
-- This single baseline replaces the former V1..V12 migration chain, squashed
-- while the product had no real users. It reflects the exact final schema those
-- migrations produced (verified by pg_dump parity), reorganized into readable
-- feature sections. New schema changes continue from V2 onward.
--
-- Conventions:
--   * IDs: UUID v7, generated by the application (Hibernate @UuidGenerator).
--     SQL-seeded catalog rows below use gen_random_uuid() (built into PG 13+).
--   * Timestamps: managed by the app (Spring Data @CreatedDate/@LastModifiedDate).
--     DEFAULT NOW() + the set_updated_at() trigger are a safety net for raw-SQL
--     writes outside JPA.
--   * Enums are VARCHAR(n), validated in Java — never PostgreSQL ENUM types
--     (they cause JDBC cast errors on INSERT with Hibernate 7).
--   * Colors are VARCHAR(7), never CHAR(7) — bpchar fails Hibernate validate.
--   * scope_workspace_id / scope_project_id on the taxonomy catalog: both NULL =
--     a global row; the CHECK forbids setting both. Reserved for future
--     workspace-/project-admin delegation. Queries must always filter by scope.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- SHARED TRIGGER — keeps updated_at accurate for raw-SQL writes outside JPA
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- AUTH & USERS
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id                UUID          PRIMARY KEY,
    email             VARCHAR(255)  NOT NULL UNIQUE,
    display_name      VARCHAR(100)  NOT NULL,
    avatar_url        TEXT,
    password_hash     VARCHAR(255),                          -- NULL for OAuth-only / pending-setup accounts
    status            VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    terms_accepted_at TIMESTAMPTZ,                           -- NULL for pre-terms accounts
    demo_seeded_at    TIMESTAMPTZ,                           -- NULL = demo seeding pending
    system_role       VARCHAR(20)   NOT NULL DEFAULT 'USER', -- ADMIN | USER
    onboarded_at      TIMESTAMPTZ                            -- NULL = first-login onboarding pending
);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- OAuth 2.0 linked accounts (Google, GitHub, …)
CREATE TABLE oauth_accounts (
    id               UUID         PRIMARY KEY,
    user_id          UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider         VARCHAR(50)  NOT NULL,                  -- 'google', 'github'
    provider_user_id VARCHAR(255) NOT NULL,
    access_token     TEXT,
    refresh_token    TEXT,
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE(provider, provider_user_id)
);

-- JWT refresh tokens — SHA-256 hash stored, never the raw token
CREATE TABLE refresh_tokens (
    id         UUID        PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Email verification flow
CREATE TABLE email_verifications (
    id          UUID        PRIMARY KEY,
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    verified_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Password reset flow (also powers admin-issued account setup links)
CREATE TABLE password_resets (
    id         UUID        PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- WORKSPACES (tenant boundary)
-- ---------------------------------------------------------------------------

CREATE TABLE workspaces (
    id         UUID         PRIMARY KEY,
    slug       VARCHAR(100) NOT NULL UNIQUE,                 -- URL-safe identifier
    name       VARCHAR(255) NOT NULL,
    created_by UUID         NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_workspaces_updated_at
    BEFORE UPDATE ON workspaces
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE workspace_members (
    id           UUID        PRIMARY KEY,
    workspace_id UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role         VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(workspace_id, user_id)
);

CREATE TABLE workspace_invites (
    id           UUID         PRIMARY KEY,
    workspace_id UUID         NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    email        VARCHAR(255) NOT NULL,
    role         VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    token_hash   VARCHAR(64)  NOT NULL UNIQUE,
    invited_by   UUID         NOT NULL REFERENCES users(id),
    expires_at   TIMESTAMPTZ  NOT NULL,
    accepted_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- PROJECTS
-- Taxonomy-binding FKs (workflow/priority_set/field_set/issue_type_set) are
-- added at the very end — those tables are created below this point.
-- ---------------------------------------------------------------------------

CREATE TABLE projects (
    id                UUID         PRIMARY KEY,
    workspace_id      UUID         NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name              VARCHAR(255) NOT NULL,
    key               VARCHAR(10)  NOT NULL,                 -- e.g. "PROJ", "HMS"
    description       TEXT,
    archived_at       TIMESTAMPTZ,
    issue_seq         BIGINT       NOT NULL DEFAULT 0,       -- native counter for issue numbers (updatable=false in JPA)
    created_by        UUID         NOT NULL REFERENCES users(id),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    workflow_id       UUID,                                  -- NULL = system default (see FKs at end)
    priority_set_id   UUID,
    field_set_id      UUID,
    issue_type_set_id UUID,
    UNIQUE(workspace_id, key)
);

CREATE TRIGGER trg_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE project_members (
    id         UUID        PRIMARY KEY,
    project_id UUID        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(project_id, user_id)
);

-- ---------------------------------------------------------------------------
-- GLOBAL TAXONOMY CATALOG (statuses / priorities / issue types)
-- scope_workspace_id / scope_project_id NULL = global; CHECK forbids both set.
-- ---------------------------------------------------------------------------

CREATE TABLE statuses (
    id                 UUID         PRIMARY KEY,
    scope_workspace_id UUID         REFERENCES workspaces(id) ON DELETE CASCADE,
    name               VARCHAR(100) NOT NULL,
    category           VARCHAR(20)  NOT NULL,                -- TO DO | IN_PROGRESS | DONE
    color              VARCHAR(7)   NOT NULL DEFAULT '#6B7280',
    position           SMALLINT     NOT NULL DEFAULT 0,
    archived_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    scope_project_id   UUID         REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT statuses_scope_ck CHECK (scope_workspace_id IS NULL OR scope_project_id IS NULL),
    CONSTRAINT statuses_scope_name_key UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, name)
);

CREATE TABLE priorities (
    id                 UUID         PRIMARY KEY,
    scope_workspace_id UUID         REFERENCES workspaces(id) ON DELETE CASCADE,
    name               VARCHAR(100) NOT NULL,
    color              VARCHAR(7)   NOT NULL DEFAULT '#8B8680',
    icon               VARCHAR(50),                          -- lucide icon name
    position           SMALLINT     NOT NULL DEFAULT 0,
    archived_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    scope_project_id   UUID         REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT priorities_scope_ck CHECK (scope_workspace_id IS NULL OR scope_project_id IS NULL),
    CONSTRAINT priorities_scope_name_key UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, name)
);

CREATE TABLE issue_types (
    id                 UUID         PRIMARY KEY,
    scope_workspace_id UUID         REFERENCES workspaces(id) ON DELETE CASCADE,
    name               VARCHAR(100) NOT NULL,
    color              VARCHAR(7)   NOT NULL DEFAULT '#6B7280',
    icon               VARCHAR(50),
    position           SMALLINT     NOT NULL DEFAULT 0,
    archived_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    scope_project_id   UUID         REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT issue_types_scope_ck CHECK (scope_workspace_id IS NULL OR scope_project_id IS NULL),
    CONSTRAINT issue_types_scope_name_key UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, name)
);

-- ---------------------------------------------------------------------------
-- WORKFLOWS (reusable status set + transitions, bound per project)
-- ---------------------------------------------------------------------------

CREATE TABLE workflows (
    id                 UUID         PRIMARY KEY,
    scope_workspace_id UUID         REFERENCES workspaces(id) ON DELETE CASCADE,
    name               VARCHAR(100) NOT NULL,
    description        TEXT,
    is_system_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    scope_project_id   UUID         REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT workflows_scope_ck CHECK (scope_workspace_id IS NULL OR scope_project_id IS NULL),
    CONSTRAINT workflows_scope_name_key UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, name)
);

CREATE TABLE workflow_statuses (
    id          UUID     PRIMARY KEY,
    workflow_id UUID     NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
    status_id   UUID     NOT NULL REFERENCES statuses(id) ON DELETE CASCADE,
    position    SMALLINT NOT NULL DEFAULT 0,                 -- board column order
    UNIQUE(workflow_id, status_id)
);

-- from_status_id NULL = "from any status" (wildcard grant)
CREATE TABLE workflow_transitions (
    id             UUID PRIMARY KEY,
    workflow_id    UUID NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
    from_status_id UUID REFERENCES statuses(id) ON DELETE CASCADE,
    to_status_id   UUID NOT NULL REFERENCES statuses(id) ON DELETE CASCADE,
    UNIQUE NULLS NOT DISTINCT (workflow_id, from_status_id, to_status_id)
);

-- ---------------------------------------------------------------------------
-- PRIORITY SETS (reusable priority list, bound per project)
-- ---------------------------------------------------------------------------

CREATE TABLE priority_sets (
    id                 UUID         PRIMARY KEY,
    scope_workspace_id UUID         REFERENCES workspaces(id) ON DELETE CASCADE,
    name               VARCHAR(100) NOT NULL,
    is_system_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    scope_project_id   UUID         REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT priority_sets_scope_ck CHECK (scope_workspace_id IS NULL OR scope_project_id IS NULL),
    CONSTRAINT priority_sets_scope_name_key UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, name)
);

CREATE TABLE priority_set_items (
    id          UUID     PRIMARY KEY,
    set_id      UUID     NOT NULL REFERENCES priority_sets(id) ON DELETE CASCADE,
    priority_id UUID     NOT NULL REFERENCES priorities(id) ON DELETE CASCADE,
    position    SMALLINT NOT NULL DEFAULT 0,
    is_default  BOOLEAN  NOT NULL DEFAULT FALSE,             -- default for new issues
    UNIQUE(set_id, priority_id)
);

-- ---------------------------------------------------------------------------
-- CUSTOM FIELDS (definitions + reusable field sets, bound per project)
-- ---------------------------------------------------------------------------

CREATE TABLE field_defs (
    id                 UUID         PRIMARY KEY,
    scope_workspace_id UUID         REFERENCES workspaces(id) ON DELETE CASCADE,
    key                VARCHAR(50)  NOT NULL,                -- immutable machine name (snake_case)
    name               VARCHAR(100) NOT NULL,
    type               VARCHAR(20)  NOT NULL,                -- TEXT|TEXTAREA|NUMBER|DATE|SELECT|MULTI_SELECT|USER|CHECKBOX|URL
    config             JSONB,                                -- {"options":[{id,label,color}],"min","max"}
    description        TEXT,
    archived_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    scope_project_id   UUID         REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT field_defs_scope_ck CHECK (scope_workspace_id IS NULL OR scope_project_id IS NULL),
    CONSTRAINT field_defs_scope_key_key  UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, key),
    CONSTRAINT field_defs_scope_name_key UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, name)
);

CREATE TABLE field_sets (
    id                 UUID         PRIMARY KEY,
    scope_workspace_id UUID         REFERENCES workspaces(id) ON DELETE CASCADE,
    name               VARCHAR(100) NOT NULL,
    is_system_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    scope_project_id   UUID         REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT field_sets_scope_ck CHECK (scope_workspace_id IS NULL OR scope_project_id IS NULL),
    CONSTRAINT field_sets_scope_name_key UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, name)
);

CREATE TABLE field_set_items (
    id             UUID     PRIMARY KEY,
    set_id         UUID     NOT NULL REFERENCES field_sets(id) ON DELETE CASCADE,
    field_id       UUID     NOT NULL REFERENCES field_defs(id) ON DELETE CASCADE,
    position       SMALLINT NOT NULL DEFAULT 0,
    required       BOOLEAN  NOT NULL DEFAULT FALSE,          -- must be filled on create, can't be cleared
    show_on_create BOOLEAN  NOT NULL DEFAULT TRUE,           -- rendered in the create form
    UNIQUE(set_id, field_id)
);

-- ---------------------------------------------------------------------------
-- ISSUE TYPE SETS (reusable type list, bound per project)
-- ---------------------------------------------------------------------------

CREATE TABLE issue_type_sets (
    id                 UUID         PRIMARY KEY,
    scope_workspace_id UUID         REFERENCES workspaces(id) ON DELETE CASCADE,
    name               VARCHAR(100) NOT NULL,
    is_system_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    scope_project_id   UUID         REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT issue_type_sets_scope_ck CHECK (scope_workspace_id IS NULL OR scope_project_id IS NULL),
    CONSTRAINT issue_type_sets_scope_name_key UNIQUE NULLS NOT DISTINCT (scope_workspace_id, scope_project_id, name)
);

CREATE TABLE issue_type_set_items (
    id       UUID     PRIMARY KEY,
    set_id   UUID     NOT NULL REFERENCES issue_type_sets(id) ON DELETE CASCADE,
    type_id  UUID     NOT NULL REFERENCES issue_types(id) ON DELETE CASCADE,
    position SMALLINT NOT NULL DEFAULT 0,                    -- display order in issue forms
    UNIQUE(set_id, type_id)
);

-- ---------------------------------------------------------------------------
-- ISSUES
-- ---------------------------------------------------------------------------

CREATE TABLE issues (
    id          UUID         PRIMARY KEY,
    workspace_id UUID        NOT NULL REFERENCES workspaces(id),   -- denormalized for tenant scoping
    project_id  UUID         NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    number      BIGINT       NOT NULL,                             -- project-scoped: PROJECT_KEY-number
    title       VARCHAR(500) NOT NULL,
    description TEXT,
    -- NOTE: type_id/status_id intentionally carry NO foreign key. The original
    -- V1 FKs were dropped by V6's `DROP TABLE statuses/issue_types CASCADE` and
    -- never recreated; referential integrity here is enforced at the app layer
    -- (ProjectConfigService). Adding FKs back is a deliberate, separately-tested
    -- change (it would make admin delete-with-remap fail on dangling refs).
    type_id     UUID         NOT NULL,
    status_id   UUID         NOT NULL,
    assignee_id UUID         REFERENCES users(id),
    reporter_id UUID         NOT NULL REFERENCES users(id),
    parent_id   UUID         REFERENCES issues(id),               -- for sub-tasks
    position    BIGINT       NOT NULL DEFAULT 0,                  -- board ordering; gaps of 1000
    due_date    DATE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version     INT          NOT NULL DEFAULT 0,                  -- optimistic locking
    priority_id UUID         NOT NULL REFERENCES priorities(id),
    UNIQUE(project_id, number)
);

CREATE TRIGGER trg_issues_updated_at
    BEFORE UPDATE ON issues
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE issue_comments (
    id         UUID        PRIMARY KEY,
    issue_id   UUID        NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    author_id  UUID        NOT NULL REFERENCES users(id),
    body       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ                                        -- soft delete
);

CREATE TRIGGER trg_issue_comments_updated_at
    BEFORE UPDATE ON issue_comments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- @mentions inside a comment body (drives notifications)
CREATE TABLE comment_mentions (
    id         UUID        PRIMARY KEY,
    comment_id UUID        NOT NULL REFERENCES issue_comments(id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(comment_id, user_id)
);

CREATE TABLE issue_field_values (
    id         UUID        PRIMARY KEY,
    issue_id   UUID        NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    field_id   UUID        NOT NULL REFERENCES field_defs(id) ON DELETE CASCADE,
    value      JSONB       NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(issue_id, field_id)
);

CREATE TABLE issue_history (
    id         UUID         PRIMARY KEY,
    issue_id   UUID         NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    changed_by UUID         NOT NULL REFERENCES users(id),
    field      VARCHAR(50)  NOT NULL,
    old_value  TEXT,
    new_value  TEXT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE issue_attachments (
    id           UUID         PRIMARY KEY,
    issue_id     UUID         NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    filename     VARCHAR(255) NOT NULL,
    storage_key  TEXT         NOT NULL,                            -- server-generated key in the FileStorage backend
    size_bytes   BIGINT       NOT NULL CHECK (size_bytes > 0),
    content_type VARCHAR(255) NOT NULL,
    uploaded_by  UUID         NOT NULL REFERENCES users(id),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- NOTIFICATIONS
-- ---------------------------------------------------------------------------

CREATE TABLE notifications (
    id         UUID        PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type       VARCHAR(50) NOT NULL,
    title      VARCHAR(255) NOT NULL,
    body       TEXT,
    link       TEXT,
    read_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- PROJECT ↔ TAXONOMY BINDINGS (added here to break the projects↔sets cycle)
-- NULL binding = the is_system_default row of each dimension.
-- ---------------------------------------------------------------------------

ALTER TABLE projects ADD CONSTRAINT projects_workflow_id_fkey       FOREIGN KEY (workflow_id)       REFERENCES workflows(id);
ALTER TABLE projects ADD CONSTRAINT projects_priority_set_id_fkey   FOREIGN KEY (priority_set_id)   REFERENCES priority_sets(id);
ALTER TABLE projects ADD CONSTRAINT projects_field_set_id_fkey      FOREIGN KEY (field_set_id)      REFERENCES field_sets(id);
ALTER TABLE projects ADD CONSTRAINT projects_issue_type_set_id_fkey FOREIGN KEY (issue_type_set_id) REFERENCES issue_type_sets(id);

-- ---------------------------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------------------------

-- Auth
CREATE INDEX idx_refresh_tokens_user      ON refresh_tokens(user_id);
CREATE INDEX idx_email_verifications_user ON email_verifications(user_id);
CREATE INDEX idx_password_resets_user     ON password_resets(user_id);

-- Workspaces
CREATE INDEX idx_workspace_members_workspace ON workspace_members(workspace_id);
CREATE INDEX idx_workspace_members_user      ON workspace_members(user_id);
CREATE INDEX idx_workspace_invites_workspace ON workspace_invites(workspace_id);
CREATE INDEX idx_workspace_invites_email     ON workspace_invites(email);

-- Projects
CREATE INDEX idx_projects_workspace       ON projects(workspace_id);
CREATE INDEX idx_projects_workflow        ON projects(workflow_id)       WHERE workflow_id       IS NOT NULL;
CREATE INDEX idx_projects_priority_set    ON projects(priority_set_id)   WHERE priority_set_id   IS NOT NULL;
CREATE INDEX idx_projects_field_set       ON projects(field_set_id)      WHERE field_set_id      IS NOT NULL;
CREATE INDEX idx_projects_issue_type_set  ON projects(issue_type_set_id) WHERE issue_type_set_id IS NOT NULL;
CREATE INDEX idx_project_members_project  ON project_members(project_id);
CREATE INDEX idx_project_members_user     ON project_members(user_id);

-- Taxonomy catalog (partial: scope lookups)
CREATE INDEX idx_statuses_scope_workspace         ON statuses(scope_workspace_id)         WHERE scope_workspace_id IS NOT NULL;
CREATE INDEX idx_statuses_scope_project           ON statuses(scope_project_id)           WHERE scope_project_id   IS NOT NULL;
CREATE INDEX idx_priorities_scope_workspace       ON priorities(scope_workspace_id)       WHERE scope_workspace_id IS NOT NULL;
CREATE INDEX idx_priorities_scope_project         ON priorities(scope_project_id)         WHERE scope_project_id   IS NOT NULL;
CREATE INDEX idx_issue_types_scope_workspace      ON issue_types(scope_workspace_id)      WHERE scope_workspace_id IS NOT NULL;
CREATE INDEX idx_issue_types_scope_project        ON issue_types(scope_project_id)        WHERE scope_project_id   IS NOT NULL;
CREATE INDEX idx_workflows_scope_workspace        ON workflows(scope_workspace_id)        WHERE scope_workspace_id IS NOT NULL;
CREATE INDEX idx_workflows_scope_project          ON workflows(scope_project_id)          WHERE scope_project_id   IS NOT NULL;
CREATE INDEX idx_priority_sets_scope_workspace    ON priority_sets(scope_workspace_id)    WHERE scope_workspace_id IS NOT NULL;
CREATE INDEX idx_priority_sets_scope_project      ON priority_sets(scope_project_id)      WHERE scope_project_id   IS NOT NULL;
CREATE INDEX idx_field_defs_scope_workspace       ON field_defs(scope_workspace_id)       WHERE scope_workspace_id IS NOT NULL;
CREATE INDEX idx_field_defs_scope_project         ON field_defs(scope_project_id)         WHERE scope_project_id   IS NOT NULL;
CREATE INDEX idx_field_sets_scope_workspace       ON field_sets(scope_workspace_id)       WHERE scope_workspace_id IS NOT NULL;
CREATE INDEX idx_field_sets_scope_project         ON field_sets(scope_project_id)         WHERE scope_project_id   IS NOT NULL;
CREATE INDEX idx_issue_type_sets_scope_workspace  ON issue_type_sets(scope_workspace_id)  WHERE scope_workspace_id IS NOT NULL;
CREATE INDEX idx_issue_type_sets_scope_project    ON issue_type_sets(scope_project_id)    WHERE scope_project_id   IS NOT NULL;

-- Binding children
CREATE INDEX idx_workflow_statuses_wf       ON workflow_statuses(workflow_id);
CREATE INDEX idx_workflow_statuses_status   ON workflow_statuses(status_id);
CREATE INDEX idx_workflow_transitions_wf    ON workflow_transitions(workflow_id);
CREATE INDEX idx_workflow_transitions_from  ON workflow_transitions(from_status_id) WHERE from_status_id IS NOT NULL;
CREATE INDEX idx_workflow_transitions_to    ON workflow_transitions(to_status_id);
CREATE INDEX idx_priority_set_items_set     ON priority_set_items(set_id);
CREATE INDEX idx_priority_set_items_priority ON priority_set_items(priority_id);
CREATE INDEX idx_field_set_items_set        ON field_set_items(set_id);
CREATE INDEX idx_field_set_items_field      ON field_set_items(field_id);
CREATE INDEX idx_issue_type_set_items_set   ON issue_type_set_items(set_id);
CREATE INDEX idx_issue_type_set_items_type  ON issue_type_set_items(type_id);

-- Issues
CREATE INDEX idx_issues_project          ON issues(project_id);
CREATE INDEX idx_issues_workspace        ON issues(workspace_id);
CREATE INDEX idx_issues_assignee         ON issues(assignee_id) WHERE assignee_id IS NOT NULL;
CREATE INDEX idx_issues_status           ON issues(status_id);
CREATE INDEX idx_issues_type             ON issues(type_id);
CREATE INDEX idx_issues_priority         ON issues(priority_id);
CREATE INDEX idx_issues_parent           ON issues(parent_id)   WHERE parent_id   IS NOT NULL;
CREATE INDEX idx_issues_project_position ON issues(project_id, position);

-- Issue activity
CREATE INDEX idx_issue_comments_issue    ON issue_comments(issue_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_issue_field_values_iss  ON issue_field_values(issue_id);
CREATE INDEX idx_issue_field_values_fld  ON issue_field_values(field_id);
CREATE INDEX idx_issue_history_issue     ON issue_history(issue_id, created_at DESC);

-- Notifications
CREATE INDEX idx_notifications_user      ON notifications(user_id, created_at DESC);
CREATE INDEX idx_notifications_unread    ON notifications(user_id) WHERE read_at IS NULL;

-- ---------------------------------------------------------------------------
-- SEED: global catalog + system-default bindings
-- gen_random_uuid() for SQL-seeded rows only; app-created rows use UUID v7.
-- ---------------------------------------------------------------------------

INSERT INTO statuses (id, name, category, color, position) VALUES
    (gen_random_uuid(), 'To Do',       'TODO',        '#6B7280', 0),
    (gen_random_uuid(), 'In Progress', 'IN_PROGRESS', '#3B82F6', 1),
    (gen_random_uuid(), 'Done',        'DONE',        '#10B981', 2);

INSERT INTO priorities (id, name, color, icon, position) VALUES
    (gen_random_uuid(), 'Urgent', '#B91C1C', 'chevrons-up', 0),
    (gen_random_uuid(), 'High',   '#EA580C', 'chevron-up',  1),
    (gen_random_uuid(), 'Medium', '#B45309', 'equal',       2),
    (gen_random_uuid(), 'Low',    '#64748B', 'chevron-down',3),
    (gen_random_uuid(), 'None',   '#8B8680', 'minus',       4);

INSERT INTO issue_types (id, name, color, icon, position) VALUES
    (gen_random_uuid(), 'Bug',   '#EF4444', 'bug',   0),
    (gen_random_uuid(), 'Task',  '#3B82F6', 'task',  1),
    (gen_random_uuid(), 'Story', '#8B5CF6', 'story', 2),
    (gen_random_uuid(), 'Epic',  '#F59E0B', 'epic',  3);

-- Default workflow: all three statuses, open transitions (no rows = every move allowed)
INSERT INTO workflows (id, name, description, is_system_default)
    VALUES (gen_random_uuid(), 'Default workflow',
            'To Do → In Progress → Done, all transitions allowed', TRUE);

INSERT INTO workflow_statuses (id, workflow_id, status_id, position)
    SELECT gen_random_uuid(), w.id, s.id, s.position
    FROM workflows w, statuses s
    WHERE w.is_system_default AND s.scope_workspace_id IS NULL AND s.scope_project_id IS NULL;

-- Default priority set: every global priority, "None" is the default for new issues
INSERT INTO priority_sets (id, name, is_system_default)
    VALUES (gen_random_uuid(), 'Default priorities', TRUE);

INSERT INTO priority_set_items (id, set_id, priority_id, position, is_default)
    SELECT gen_random_uuid(), ps.id, p.id, p.position, (p.name = 'None')
    FROM priority_sets ps, priorities p
    WHERE ps.is_system_default AND p.scope_workspace_id IS NULL AND p.scope_project_id IS NULL;

-- Field sets: empty system default + a sample "Engineering fields" set
INSERT INTO field_sets (id, name, is_system_default)
    VALUES (gen_random_uuid(), 'No fields', TRUE);

INSERT INTO field_defs (id, key, name, type, config, description) VALUES
    (gen_random_uuid(), 'story_points', 'Story points', 'NUMBER',
     '{"min": 0, "max": 100}',
     'Fibonacci estimate agreed at planning'),
    (gen_random_uuid(), 'severity', 'Severity', 'SELECT',
     '{"options": [
        {"id": "critical", "label": "Critical", "color": "#B91C1C"},
        {"id": "major",    "label": "Major",    "color": "#EA580C"},
        {"id": "minor",    "label": "Minor",    "color": "#64748B"}]}',
     'Impact of the defect on users'),
    (gen_random_uuid(), 'environment', 'Environment', 'MULTI_SELECT',
     '{"options": [
        {"id": "production", "label": "Production", "color": "#B91C1C"},
        {"id": "staging",    "label": "Staging",    "color": "#B45309"},
        {"id": "dev",        "label": "Dev",        "color": "#64748B"}]}',
     'Where the issue was observed');

INSERT INTO field_sets (id, name) VALUES (gen_random_uuid(), 'Engineering fields');

INSERT INTO field_set_items (id, set_id, field_id, position, required, show_on_create)
    SELECT gen_random_uuid(), fs.id, fd.id,
           CASE fd.key WHEN 'story_points' THEN 0 WHEN 'severity' THEN 1 ELSE 2 END,
           FALSE,
           fd.key <> 'environment'
    FROM field_sets fs, field_defs fd
    WHERE fs.name = 'Engineering fields' AND fd.scope_workspace_id IS NULL AND fd.scope_project_id IS NULL;

-- Issue type set: system default contains every global type (catalog order)
INSERT INTO issue_type_sets (id, name, is_system_default)
    VALUES (gen_random_uuid(), 'All types', TRUE);

INSERT INTO issue_type_set_items (id, set_id, type_id, position)
    SELECT gen_random_uuid(), s.id, t.id, t.position
    FROM issue_type_sets s, issue_types t
    WHERE s.is_system_default AND t.scope_workspace_id IS NULL AND t.scope_project_id IS NULL;
