import { describe, it, expect } from 'vitest'
import ESLINT_CONFIG_SOURCE from '../../eslint.config.js?raw'
import LINT_RUNNER_SOURCE from '../../lint.mjs?raw'
import PACKAGE_JSON_SOURCE from '../../package.json?raw'
import POM_SOURCE from '../../../../../pom.xml?raw'
import VITEST_CONFIG_SOURCE from '../../vitest.config.ts?raw'
import { RULE_NAMES } from '../../eslint-rules/index.js'
import { CLOCK_DAYS, DECLARED, DECLARED_AS_OF, verdict } from '../../lint.debt.mjs'
// The comment filter every configuration-text assertion in this repo runs first.
// It was declared here until suiteGuard.test.ts needed the same one; a second
// copy is a drift waiting for the diff that fixes one of them (HD-301).
import { code } from './source'

/**
 * **The guard on the rule set, deliberately outside the rule set (HD-300).**
 *
 * HD-300 ships one rule with real debt — every numeric `fontSize:` site in the
 * SPA, `DECLARED` of them in `lint.debt.mjs` — and it carries that debt **at the
 * sites**, as
 * `eslint-disable-next-line hamstrack/no-numeric-font-size -- HD-177`, rather
 * than in a baseline file. The argument, stated once because it is the design:
 *
 * 1. **A ceiling set at today's count only fires on a regression.** A floor
 *    equal to its population asserts nothing about the population, which is the
 *    shape two gates rejected inside HD-299.
 * 2. **Inline directives self-expire.** `reportUnusedDisableDirectives: 'error'`
 *    turns a leftover directive into a build failure of its own, so the ratchet
 *    tightens the moment a site is fixed and nobody edits a number. A baseline
 *    file has no such property; ESLint's own bulk suppressions
 *    (`--suppress-all` → `eslint-suppressions.json`) are regenerated by one flag
 *    and reviewed by nobody. Locally it is worse than that: `.gitignore` ignores
 *    `audit/**\/*.json`, so a baseline dropped in the obvious place would be
 *    **absent from a fresh clone and from CI** while looking present here.
 * 3. **A new violation in an already-dirty file is still an error.** A
 *    file-level `overrides` block would be one line per dirty file instead of
 *    one per site, and would lose exactly that.
 *
 * **Why this file is not inside `eslint.config.js`.** Everything asserted below
 * is disarmed by an edit to that config — a rule set to `'warn'`, an `ignores`
 * that grew a `**`, `reportUnusedDisableDirectives` removed. A guard living in
 * the artifact it guards goes quiet in the same commit that needs it. This one
 * runs in the vitest suite, which runs inside `mvnw verify` (HD-242), and reads
 * the config as **text**.
 */

/**
 * `DECLARED`, `DECLARED_AS_OF` and `CLOCK_DAYS` are imported, not declared here:
 * the same number is enforced by `lint.mjs` over the set ESLint actually lints
 * (`.js` and `.mjs` included, which the glob below cannot see) and by this file
 * over the `.ts`/`.tsx` sources, from outside ESLint. Two enforcers, one number —
 * `lint.debt.mjs` says why. **It may only go DOWN**; both failure messages say
 * what to write instead.
 */

/** Read the SPA sources the way the neighbouring category tests do. */
const SOURCES = import.meta.glob('../**/*.{ts,tsx}', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

/**
 * The floor on the scan itself. "Found nothing" and "looked at nothing" produce
 * the same green line, so the population is asserted before anything is asserted
 * about it.
 *
 * The glob matched **222** files on 2026-09-11, after HD-301 added its five
 * (`lint.mjs` lints more than that: it adds the `.js`/`.mjs` config and root
 * scripts). `nodeApi.test.ts` globs the same tree with the same pattern and the
 * same floor, so the two numbers are one fact. Like every floor in this ticket it
 * catches the **collapse** — a glob that resolves to nothing after a directory
 * rename — and not the drift; the slack is not a budget for deleting that many
 * files, and nothing here would notice if you did.
 */
const FILE_FLOOR = 200

/**
 * A **separate** glob, and the reason is the whole point of this file: the source
 * glob above matches `.ts`/`.tsx`, so the suppressions-file assertion written
 * against it could never have fired — planting `eslint-suppressions.json` left
 * the suite green (verified 2026-09-11, before this line existed). Not eager: only
 * the keys are needed, and the file this looks for is machine-written JSON.
 */
const SUPPRESSION_FILES = import.meta.glob('../../**/eslint-suppressions.json')

const DIRECTIVE_RE = /eslint-disable(?:-next-line|-line)?\s+([\w/-]+)([^\n]*)/g

interface Directive { file: string; line: number; rule: string; justification: string }

function directives(): Directive[] {
  const out: Directive[] = []
  for (const [file, source] of Object.entries(SOURCES)) {
    // This file quotes the directive text in prose; excluding it by name would
    // rot, so it is excluded by identity.
    if (file.endsWith('/lint/debt.test.ts')) continue
    const lines = source.split(/\r?\n/)
    lines.forEach((text, i) => {
      DIRECTIVE_RE.lastIndex = 0
      const m = DIRECTIVE_RE.exec(text)
      if (m) out.push({ file, line: i + 1, rule: m[1], justification: m[2] })
    })
  }
  return out
}

describe('the scan reads the tree it claims to read', () => {
  it('matched enough files that a green line means something', () => {
    expect(
      Object.keys(SOURCES).length,
      'the glob matched almost nothing, so every assertion below is green for free',
    ).toBeGreaterThanOrEqual(FILE_FLOOR)
  })
})

describe('the HD-177 debt record can only shrink', () => {
  it(`carries no more than ${DECLARED} directives`, () => {
    const all = directives()
    expect(
      all.length,
      `there are now ${all.length} eslint-disable directives in the SPA, over the ${DECLARED} ` +
      'declared in lint.debt.mjs. This number may only go DOWN. If you are paying HD-177 ' +
      'off, lower DECLARED to the new count and move DECLARED_AS_OF forward. If you are ' +
      'adding a suppression, do not: fix the site, or argue for the exception in the diff ' +
      'and raise DECLARED by hand so a reviewer sees it.',
    ).toBeLessThanOrEqual(DECLARED)
  })

  it('gives every directive a ticket to expire against', () => {
    const unexplained = directives()
      .filter((d) => !/HD-\d+/.test(d.justification))
      .map((d) => `${d.file}:${d.line} — ${d.rule}`)
    expect(
      unexplained,
      'a suppression with no ticket is debt nobody owns and nobody will ever come back for. ' +
      'Write it as `// eslint-disable-next-line <rule> -- HD-<n>`; ESLint parses everything ' +
      'after `--` as the justification, and lint.mjs both prints the tickets in its witness ' +
      'line and refuses a suppression that names none — over every file it lints, which is ' +
      'the half this .ts/.tsx scan cannot reach.',
    ).toEqual([])
  })

  /**
   * **The clock, and the one condition on it.** Past `CLOCK_DAYS` since
   * `DECLARED_AS_OF` this goes red — UNLESS the debt has reached 0, in which
   * case there is nothing left to park and the clock is switched off entirely
   * rather than demanding a date be restated forever. The condition is in the
   * assertion below, in plain sight, because a javadoc that promised the
   * unconditional version would be a claim wider than its mechanism — which is
   * the defect class this whole ticket is about.
   */
  it('has not let the ratchet go quiet', () => {
    const declaredAt = new Date(`${DECLARED_AS_OF}T00:00:00Z`).getTime()
    const days = Math.floor((Date.now() - declaredAt) / 86_400_000)
    expect(
      days,
      `DECLARED (${DECLARED}) was last stated on ${DECLARED_AS_OF}, ${days} days ago, and the ` +
      `debt has not moved in ${CLOCK_DAYS}. A ceiling with no clock is a permanent parking ` +
      'space. Either fix sites and lower DECLARED, or restate DECLARED_AS_OF with a reason ' +
      'on the same line — but do not leave it silent.',
    ).toBeLessThan(CLOCK_DAYS + (DECLARED === 0 ? Number.MAX_SAFE_INTEGER : 0))
  })
})

describe('the suppression escape hatch is closed from outside ESLint', () => {
  it('has no bulk-suppressions file anywhere in the tree', () => {
    const offenders = Object.keys(SUPPRESSION_FILES)
    expect(
      offenders,
      "ESLint's bulk suppressions are regenerated by one flag and reviewed by nobody, which " +
      'is precisely what HD-300 chose inline directives instead of. Delete the file and put ' +
      'the debt at the sites.',
    ).toEqual([])
  })

  it('has no --suppress flag in any script or in the pom', () => {
    expect(code(PACKAGE_JSON_SOURCE), 'a package.json script regenerates the suppressions file')
      .not.toMatch(/--suppress/)
    expect(code(LINT_RUNNER_SOURCE), 'lint.mjs regenerates the suppressions file')
      .not.toMatch(/suppress(All|-all)|suppressionsLocation/)
    expect(code(POM_SOURCE), 'the Maven lint execution regenerates the suppressions file')
      .not.toMatch(/--suppress/)
  })
})

describe('the rule set cannot be disarmed by editing its own config', () => {
  it('turns every rule on at error, and none at warn or off', () => {
    for (const name of RULE_NAMES) {
      const line = new RegExp(`'hamstrack/${name}':\\s*'([a-z]+)'`).exec(ESLINT_CONFIG_SOURCE)
      expect(line, `hamstrack/${name} is not configured at all in eslint.config.js`).not.toBeNull()
      expect(
        line?.[1],
        `hamstrack/${name} is set to '${line?.[1]}'. A trap demoted to a warning is a trap ` +
        'nobody reads, and a rule turned off is one nobody can even count. Fix the sites, or ' +
        'delete the rule and say in the diff which mechanism replaces it. (lint.mjs now exits ' +
        'non-zero on a warning too, so a downgrade written in a SOURCE file — which this ' +
        'config never sees — is red as well; this assertion covers the config half.)',
      ).toBe('error')
    }
  })

  it('keeps reportUnusedDisableDirectives at error — the thing that expires the debt', () => {
    expect(
      ESLINT_CONFIG_SOURCE,
      'without this, a directive left behind after its site is fixed is silent, and the ' +
      'inline directives stop being a self-expiring record and become a permanent one — ' +
      'exactly the baseline file HD-300 refused.',
    ).toMatch(/reportUnusedDisableDirectives:\s*'error'/)
  })

  it('ignores only the declared list', () => {
    const declared = /const IGNORED = \[([^\]]*)]/.exec(ESLINT_CONFIG_SOURCE)?.[1] ?? ''
    const entries = [...declared.matchAll(/'([^']+)'/g)].map((m) => m[1])
    expect(
      entries.sort(),
      'eslint.config.js `ignores` no longer equals its declared list. An ignores entry that ' +
      'grows a `**` takes the file count to near zero, and a bare eslint run exits 0 on that. ' +
      "lint.mjs's FILE_FLOOR is the other half of this guard; change both deliberately.",
    ).toEqual(['coverage/**', 'dist/**', 'node_modules/**'])
    // …and exactly one `ignores` key exists in the config's CODE, so a second
    // flat-config block cannot add to the ignore set without editing this line.
    expect(
      (code(ESLINT_CONFIG_SOURCE).match(/\bignores\b/g) ?? []).length,
      'eslint.config.js has more than one `ignores` key. Flat config MERGES them, so the ' +
      'declared list above is no longer the whole ignore set and a second block can hide ' +
      'the tree. Keep one, and keep it equal to IGNORED.',
    ).toBe(1)
  })
})

/**
 * **A build-config list whose widening silently grants more — both members.**
 *
 * `eslint.config.js`'s `ignores` is the other one, asserted by equality a screen
 * up. `vitest.config.ts`'s `server.fs.allow` has exactly the same property and
 * arrived in this same fix loop with no guard at all: it was widened from
 * `'../../..'` — the whole repository, `application*.properties`,
 * `data/attachments/`, `ops/`, `.claude/`, any `.env` — down to two spellings of
 * one file, and nothing in the tree said so.
 *
 * **Why it will be widened back.** The two entries are not redundant: vite 6.4.3
 * checks this import twice, once with the query (`…/pom.xml?raw`, in
 * `isServerAccessDeniedForTransform`) and once without (`cleanUrl`, on load), and
 * an exact-match entry covers only what it spells. So the next developer who
 * adds an outside file hits `Denied ID` at collection and is one keystroke from
 * restoring the parent directory, which makes the error go away and silently
 * re-grants everything. This test is the sentence that keystroke should meet.
 */
describe('the test runner reaches outside the SPA only for the files it names', () => {
  it('allows exactly the declared entries, and no directory above the root', () => {
    // Over `code()`, not the raw text: the comment above the entry quotes an
    // earlier, insufficient spelling of this very list, and a raw scan would
    // read the explanation instead of the configuration.
    const declared = /allow:\s*\[([^\]]*)]/.exec(code(VITEST_CONFIG_SOURCE))?.[1] ?? ''
    const entries = [...declared.matchAll(/'([^']+)'/g)].map((m) => m[1])
    expect(
      entries,
      'vitest.config.ts `server.fs.allow` no longer equals its declared list. A DIRECTORY ' +
      "entry — `'../../..'` is the one that was there first — hands Vite's transform " +
      'middleware the whole repository: application*.properties, data/attachments/, ops/, ' +
      '.claude/, any .env. If a new test needs a file outside src/main/frontend, give that ' +
      'FILE its own two entries (with and without `?raw`: vite checks the id twice, once ' +
      'per spelling) rather than widening to a parent, and change this list in the same diff.',
    ).toEqual(['./', '../../../pom.xml', '../../../pom.xml?raw'])
    // …and exactly one `allow` key, for the reason the `ignores` assertion gives:
    // a second one merges and the list above stops being the whole grant.
    expect(
      (code(VITEST_CONFIG_SOURCE).match(/\ballow:/g) ?? []).length,
      'vitest.config.ts has more than one `server.fs.allow`. The list asserted above is no ' +
      'longer the whole allow-list, so it no longer bounds anything. Keep one.',
    ).toBe(1)
  })
})

describe('the gate is reachable from the build', () => {
  it('is wired into the pom at the test phase, where -DskipTests reaches it', () => {
    // The last silent-drop path: an execution deleted from the pom leaves lint
    // running locally and nowhere else, and no test would notice.
    const execution = /<id>npm-lint<\/id>[\s\S]{0,400}?<\/execution>/.exec(POM_SOURCE)?.[0] ?? ''
    expect(
      execution,
      'the npm-lint execution is gone from pom.xml, so `mvnw verify` no longer lints the SPA ' +
      'and nothing else would have said so. Restore it (goal `npm`, phase `test`, arguments ' +
      '`run lint`) — a `test`-phase binding specifically, because frontend-maven-plugin ' +
      'honours -DskipTests only for an execution bound to one of its two testing phases, ' +
      '`test` or `integration-test` (AbstractFrontendMojo.isTestingPhase, 1.15.1). Note it ' +
      'binds that flag to ${skipTests} ONLY: -Dmaven.test.skip=true silences surefire and ' +
      'would NOT silence this.',
    ).not.toBe('')
    expect(
      execution,
      'the npm-lint execution moved off the `test` phase, so -DskipTests no longer switches ' +
      'it off and the Dockerfile`s `package -DskipTests` now pays for a gate CI already ran.',
    ).toMatch(/<phase>test<\/phase>/)
    expect(
      execution,
      'the npm-lint execution no longer runs `npm run lint`. A different argument means the ' +
      'Maven path and the local loop are running different things, and only one of them is ' +
      'the gate lint.mjs implements.',
    ).toMatch(/<arguments>run lint<\/arguments>/)
  })

  it('declares npm-lint before npm-test, which is the only thing that orders them', () => {
    // Same phase, so Maven runs them in DECLARATION order — there is no other
    // handle. The pom claims this in prose; without this line a reorder is
    // silent and costs a developer the 45-70s vitest run before a ~5s verdict.
    const lintAt = POM_SOURCE.indexOf('<id>npm-lint</id>')
    const testAt = POM_SOURCE.indexOf('<id>npm-test</id>')
    expect(lintAt, 'npm-lint is not in pom.xml at all').toBeGreaterThan(-1)
    expect(testAt, 'npm-test is not in pom.xml at all').toBeGreaterThan(-1)
    expect(
      lintAt,
      'npm-test is now declared before npm-lint. Both are bound to `test`, and within a ' +
      'phase Maven runs executions in declaration order, so the cheap gate (~5s) now ' +
      'reports after the expensive one (~45-70s). Move the npm-lint execution back above ' +
      'npm-test, or delete the claim in the pom comment that says it is first.',
    ).toBeLessThan(testAt)
  })

  it('has a lint script that is the runner, not a bare eslint', () => {
    const scripts = JSON.parse(PACKAGE_JSON_SOURCE).scripts as Record<string, string>
    expect(
      scripts.lint,
      'a bare `eslint .` exits 0 when its ignores swallow the tree, which is the failure ' +
      'lint.mjs exists to make loud. Keep the script pointing at the runner.',
    ).toBe('node lint.mjs')
    // The other rule this repo already enforces from the JUnit side: no script
    // may invoke tsc without -b. Asserted here too so the frontend half is not
    // only checked from Java (VacuousVerificationRulesTest).
    for (const [name, command] of Object.entries(scripts)) {
      expect(command, `script \`${name}\` runs tsc without -b, which type-checks zero files`)
        .not.toMatch(/\btsc\b(?!\s+(?:-b|--build)\b)/)
    }
  })

  it('keeps lint.mjs asserting a file floor', () => {
    expect(
      LINT_RUNNER_SOURCE,
      'lint.mjs no longer asserts a floor on the number of files linted. Without it the run ' +
      'is exactly as green when it lints 3 files as when it lints the whole SPA, and the ' +
      'exit code cannot tell you which happened.',
    ).toMatch(/FILE_FLOOR/)
    // …and it is the number actually handed to the verdict, whose refusal of a
    // count below it is driven with fixtures below. A FILE_FLOOR declared and
    // passed to nobody is a constant, not a floor.
    expect(
      code(LINT_RUNNER_SOURCE),
      'lint.mjs declares FILE_FLOOR but no longer passes it to verdict(), so the floor is ' +
      'enforced by nothing and a run that lints 3 files is green again.',
    ).toMatch(/floor: FILE_FLOOR/)
    expect(
      code(LINT_RUNNER_SOURCE),
      'lint.mjs no longer passes the number of files it linted to verdict(), so the floor ' +
      'is compared against something other than this run.',
    ).toMatch(/fileCount: results\.length/)
    expect(code(LINT_RUNNER_SOURCE), 'a cache turns a clean run into a claim about a previous one')
      .not.toMatch(/--cache|cache:\s*true/)
  })

  /**
   * **The refusals `lint.mjs` owns *because this file cannot see them*,** driven
   * with numbers rather than matched as text: the `.ts`/`.tsx` glob above misses
   * a suppression in a `.js`/`.mjs` file, and no directive regex matches a
   * severity downgraded by an inline eslint configuration comment.
   *
   * Text matching was tried first and is what makes this the fixture version:
   * the pattern for the warning refusal also matched the line deciding whether
   * to print the stylish report, so deleting the refusal left the assertion
   * **green** (measured 2026-09-11). The decision therefore lives in `verdict`,
   * a pure function, and the only thing still asserted as text is that
   * `lint.mjs` calls it and exits on what it returns.
   */
  const CLEAN = {
    fileCount: 231, floor: 200, errors: 0, warnings: 0, suppressed: DECLARED, unticketed: [],
  }

  it('passes a clean run and refuses each way of verifying less than it looks like', () => {
    expect(verdict(CLEAN), 'a clean run is being refused — every gate below is now noise')
      .toEqual([])

    const cases: [string, Parameters<typeof verdict>[0], RegExp][] = [
      ['a run that linted almost nothing', { ...CLEAN, fileCount: 13 }, /floor is 200/],
      ['a suppression over the ceiling', { ...CLEAN, suppressed: DECLARED + 1 }, /may only go DOWN/],
      ['a suppression naming no ticket', { ...CLEAN, unticketed: ['x.js:1 — r'] }, /name no ticket/],
      ['a severity downgraded in a source file', { ...CLEAN, warnings: 1 }, /warning\(s\)/],
      ['a rule violation the run printed and shrugged at', { ...CLEAN, errors: 1 }, /error\(s\)/],
    ]
    for (const [what, run, expected] of cases) {
      const out = verdict(run)
      expect(out.length, `verdict() accepted ${what}, so \`npm run lint\` exits 0 on it`).toBe(1)
      expect(out[0], `the refusal for ${what} no longer says what happened`).toMatch(expected)
    }
  })

  /**
   * **A caller that forgot to say something, which is not a case TypeScript can
   * see.** `lint.mjs` is inside no `tsc -b` project — `tsconfig.app.json` covers
   * `src`, `tsconfig.node.json` the two vite configs — so `lint.debt.d.mts`
   * checks the fixtures on this line and never the real call. Every refusal
   * above is `>` or `<`, both FALSE against `undefined`, so an omitted count
   * used to delete its own check in silence: measured 2026-09-11, omitting
   * `warnings`, `suppressed` or `fileCount` each produced **0 refusals**.
   *
   * The casts are the assertion. Each fixture is a shape the type forbids and
   * the runtime must still refuse, so it is written as one — remove the runtime
   * guard and these go red while `tsc -b` stays silent, which is the whole
   * relationship between the two.
   */
  it('refuses a run that did not tell it everything, rather than judging the gaps', () => {
    const malformed: [string, unknown, RegExp][] = [
      ['a run missing its warning count', { ...CLEAN, warnings: undefined }, /no warnings/],
      ['a run missing its error count', { ...CLEAN, errors: undefined }, /no errors/],
      ['a run missing its suppression count', { ...CLEAN, suppressed: undefined }, /no suppressed/],
      ['a run missing its file count', { ...CLEAN, fileCount: undefined }, /no fileCount/],
      ['a run missing its floor', { ...CLEAN, floor: undefined }, /no floor/],
      ['a run whose count arrived as text', { ...CLEAN, warnings: '0' }, /no warnings/],
      ['a run whose count is NaN', { ...CLEAN, fileCount: NaN }, /no fileCount/],
      ['a run missing its unticketed list', { ...CLEAN, unticketed: undefined }, /no unticketed/],
    ]
    for (const [what, run, expected] of malformed) {
      const out = verdict(run as Parameters<typeof verdict>[0])
      expect(
        out.length,
        `verdict() accepted ${what} and judged the rest anyway. A missing count is not a ` +
        'zero: every check is a comparison, a comparison against undefined is false, and ' +
        'the check disappears instead of firing. Refuse the run.',
      ).toBe(1)
      expect(out[0], `the refusal for ${what} no longer names the missing input`).toMatch(expected)
    }
  })

  it('keeps lint.mjs wired to that verdict', () => {
    expect(
      code(LINT_RUNNER_SOURCE),
      'lint.mjs no longer imports the verdict from lint.debt.mjs. A second copy of the ' +
      'refusals — or of DECLARED — drifts the first time one enforcer is updated and the ' +
      'other is not.',
    ).toMatch(/from '\.\/lint\.debt\.mjs'/)
    expect(
      code(LINT_RUNNER_SOURCE),
      'lint.mjs no longer calls verdict(), so every refusal above is computed by nobody.',
    ).toMatch(/verdict\(\{/)
    /**
     * **Anchored to the whole line, because the previous pattern was not.** It
     * was `/failures\.length > 0\) process\.exit\(1\)/`, which the then-shipped
     * `if (errors > 0 || failures.length > 0) process.exit(1)` satisfied — and
     * so did the strictly weaker line left behind when the first term is
     * deleted. Measured 2026-09-11: with that deletion, a real
     * `no-numeric-font-size` violation was printed, `npm run lint` exited 0, and
     * all 21 tests here were green. `errors` is now inside `verdict`, so this
     * line has one term and can be pinned in full; a second term belongs in
     * `verdict`, where the fixtures above can drive it.
     */
    expect(
      code(LINT_RUNNER_SOURCE),
      'lint.mjs no longer exits non-zero on exactly what verdict() returned, and on nothing ' +
      'else. Printing a refusal and exiting 0 is the same green build as not checking at ' +
      'all; and a second term on this line is a decision no fixture can reach, which is how ' +
      'the errors check came to be deletable. Write `if (failures.length > 0) ' +
      'process.exit(1)` and put any new condition inside verdict().',
    ).toMatch(/^if \(failures\.length > 0\) process\.exit\(1\)$/m)
  })

  /**
   * **The one argument that is a value rather than a count, and it is
   * load-bearing.** `FILE_FLOOR` is 200 against a population of 231, chosen
   * slack so it catches a collapse — which means narrowing `TARGETS` to
   * `['src']` lints 217 files, clears the floor, exits 0, and makes every
   * `.js`/`.mjs` suppression outside `src` invisible to the ticketless-
   * suppression refusal that exists to see them. Measured 2026-09-11 by
   * planting exactly that, with a ticketless suppression in `eslint.config.js`:
   * `217 files linted (floor 200) · 0 errors · 0 warnings · 204 suppressed`,
   * exit 0, 21/21 green. No floor can catch this; only the value can be named.
   */
  it('keeps lint.mjs pointed at the whole tree, which no floor can check', () => {
    expect(
      code(LINT_RUNNER_SOURCE),
      "lint.mjs no longer lints '.'. Narrowing TARGETS to a subdirectory still clears " +
      'FILE_FLOOR — the floor has deliberate slack and catches a collapse, not a narrowing — ' +
      'so the run stays green while every .js/.mjs file outside it, including this repo`s ' +
      'own config and root scripts, is linted by nobody and its suppressions are counted by ' +
      'nobody. The ignore set is eslint.config.js`s IGNORED list, asserted above; this is ' +
      'the other end of the same guard.',
    ).toMatch(/^const TARGETS = \['\.']$/m)
  })
})
